/* Northstar local client — data is stored in your PocketBase server. */
const PB_URL = 'https://tumid-kiltlike-maia.ngrok-free.dev';
const pb = new PocketBase(PB_URL);
// ngrok's free browser-warning page returns HTML without PocketBase CORS headers.
// This header makes API calls reach PocketBase itself, without changing the server.
pb.beforeSend = function (url, options) {
  options.headers = { ...(options.headers || {}), 'ngrok-skip-browser-warning': 'true' };
  return { url, options };
};
const money = new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'});
const esc = value => String(value ?? '').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const fmt = value => `${value < 0 ? '−' : '+'}${money.format(Math.abs(value))}`;
let transactions = [], accounts = [], categories = [], budgets = [], goals = [], debts = [], recurring = [], investmentAccounts = [], holdings = [];
let transactionFilter = 'all';
let displayedMonth = new Date();

const titles={dashboard:'Good morning, Justin <span>☀</span>',transactions:'Transactions',budget:'July budget',loans:'Loans & mortgages',investments:'Savings & investing',bills:'Bills & recurring',scenario:'Scenario lab',reports:'Reports',learn:'Learn'};
document.querySelectorAll('[data-page]').forEach(a=>a.addEventListener('click',e=>{e.preventDefault();showPage(a.dataset.page)}));
document.querySelectorAll('[data-go]').forEach(b=>b.addEventListener('click',()=>showPage(b.dataset.go)));
function showPage(id){document.querySelectorAll('.page').forEach(p=>p.classList.remove('active-page'));document.getElementById(id).classList.add('active-page');document.querySelectorAll('[data-page]').forEach(x=>x.classList.toggle('active',x.dataset.page===id));document.getElementById('page-title').innerHTML=titles[id];window.scrollTo({top:0,behavior:'smooth'});}

function toast(message,isError=false){let t=document.getElementById('toast');if(!t){t=document.createElement('div');t.id='toast';t.className='toast';document.body.append(t)}t.textContent=message;t.classList.toggle('error',isError);t.classList.add('show');setTimeout(()=>t.classList.remove('show'),3500)}
async function getAll(collection,options={}) { try { return await pb.collection(collection).getFullList({sort:'-created',...options}); } catch (err) { console.warn(collection,err); return []; } }
function nameById(items,id,fallback='Uncategorized'){const x=items.find(item=>item.id===id);return x?.name||fallback}
function renderTransactions(){
  const activity=document.getElementById('activity-list'), table=document.getElementById('transaction-table');
  const visible=transactions.filter(t=>transactionFilter==='all'||(transactionFilter==='income'?t.amount>0:transactionFilter==='expense'?t.amount<0:t.kind===transactionFilter));
  const rows=transactions.slice(0,4).map(t=>`<div class="activity-row"><span class="activity-icon">${t.amount<0?'•':'$'}</span><div><b>${esc(t.merchant||t.description||'Transaction')}</b><p>${esc(nameById(categories,t.category,t.kind||'Other'))} · ${new Date(t.date).toLocaleDateString('en-US',{month:'short',day:'numeric'})}</p></div><strong class="${t.amount<0?'negative':'good'}">${fmt(t.amount)}</strong></div>`).join('') || '<p class="empty">No transactions yet. Add your first one to get started.</p>';
  activity.innerHTML=rows;
  table.innerHTML=visible.map(t=>`<div class="table-row"><span>${new Date(t.date).toLocaleDateString('en-US',{month:'short',day:'numeric'})}</span><span class="merchant"><i class="merchant-icon">${t.amount<0?'•':'$'}</i><b>${esc(t.merchant||t.description||'Transaction')}</b></span><span>${esc(nameById(categories,t.category,t.kind||'Other'))}</span><span>${esc(nameById(accounts,t.account,'—'))}</span><strong class="${t.amount<0?'negative':'good'}">${fmt(t.amount)}</strong></div>`).join('')||'<p class="empty">No transactions yet.</p>';
}
function renderBudget(){const lines=budgets.map(b=>`<div class="budget-line"><span>${esc(nameById(categories,b.category))}</span><div class="progress green"><i style="width:100%"></i></div><b>${money.format(b.planned_amount||0)}</b></div>`).join('')||'<p class="empty">No budget categories saved yet.</p>';document.querySelectorAll('.budget-columns .card').forEach((card,i)=>{if(i===0)card.innerHTML=`<div class="card-title"><h2>Planned categories</h2><button class="text-btn" data-create="monthly_budgets">+ Add</button></div>${lines}`});}
function renderDebts(){const list=document.querySelector('.loans-list');if(!list)return;list.innerHTML=`<div class="card-title"><h2>All debts</h2><button class="text-btn" data-create="debts">+ Add debt</button></div>${debts.map(d=>`<div class="debt-row"><span class="debt-round blue">${esc((d.name||'D')[0])}</span><div><b>${esc(d.name)}</b><p>${d.interest_rate||0}% APR · ${money.format(d.minimum_payment||0)}/mo</p></div><strong>${money.format(d.current_balance||0)}</strong><span class="progress tiny"><i style="width:45%"></i></span><button>›</button></div>`).join('')||'<p class="empty">No loans or debts saved yet.</p>'}`}
function renderBills(){const box=document.querySelector('.upcoming');if(!box)return;box.innerHTML=`<div class="card-title"><h2>Coming up</h2><button class="text-btn" data-create="recurring_items">+ Add bill</button></div>${recurring.slice(0,6).map(r=>`<div class="bill-row"><span class="bill-logo loan">${esc((r.name||'B')[0])}</span><div><b>${esc(r.name)}</b><p>${r.next_due_date?new Date(r.next_due_date).toLocaleDateString('en-US',{month:'short',day:'numeric'}):'No due date'} · ${esc(r.frequency||'monthly')}</p></div><strong>${money.format(Math.abs(r.amount||0))}</strong></div>`).join('')||'<p class="empty">No recurring bills saved yet.</p>'}`}
function renderInvestments(){const grid=document.querySelector('.account-grid');if(!grid)return;const merged=[...accounts.filter(a=>['savings','retirement','brokerage'].includes(a.type)),...investmentAccounts];grid.innerHTML=merged.map(a=>`<article class="card account-card"><span class="account-logo savings-logo">◇</span><p>${esc((a.account_type||a.type||'account').toUpperCase())}</p><h2>${esc(a.name||nameById(accounts,a.account,'Investment account'))}</h2><strong>${money.format(a.current_value||a.balance||0)}</strong><div><span>${a.monthly_contribution?`${money.format(a.monthly_contribution)}/mo`:''}</span><small>${esc(a.institution||'')}</small></div></article>`).join('')||'<p class="empty">No savings or investment accounts saved yet.</p>'}
function renderDashboard(){const start=new Date(displayedMonth.getFullYear(),displayedMonth.getMonth(),1),end=new Date(displayedMonth.getFullYear(),displayedMonth.getMonth()+1,1);const month=transactions.filter(t=>{const d=new Date(t.date);return d>=start&&d<end});const income=month.filter(t=>t.amount>0).reduce((s,t)=>s+t.amount,0), spend=Math.abs(month.filter(t=>t.amount<0).reduce((s,t)=>s+t.amount,0));const incomeNode=document.querySelector('.income strong'),spentNode=document.querySelector('.expense strong');if(incomeNode)incomeNode.textContent=money.format(income);if(spentNode)spentNode.textContent=money.format(spend);const power=document.querySelector('.spend-number');if(power)power.innerHTML=`${money.format(income-spend)}<span></span>`;document.querySelectorAll('.month-toggle strong').forEach(n=>n.textContent=displayedMonth.toLocaleDateString('en-US',{month:'long',year:'numeric'}));document.querySelector('.month-label').textContent=displayedMonth.toLocaleDateString('en-US',{month:'long',year:'numeric'}).toUpperCase()}
function renderAll(){renderTransactions();renderBudget();renderDebts();renderBills();renderInvestments();renderDashboard();bindCreateButtons()}

async function loadData(){[transactions,accounts,categories,budgets,goals,debts,recurring,investmentAccounts,holdings]=await Promise.all([getAll('transactions',{sort:'-date'}),getAll('accounts'),getAll('categories'),getAll('monthly_budgets'),getAll('goals'),getAll('debts'),getAll('recurring_items',{sort:'next_due_date'}),getAll('investment_accounts'),getAll('investment_holdings')]);const workspace=localStorage.getItem('northstar-workspace')||`${pb.authStore.record?.name||'My'}’s finances`;document.querySelector('.workspace').childNodes[1].textContent=workspace;renderAll()}

const modal=document.getElementById('modal');
function openTransaction(){document.getElementById('tx-date').value=new Date().toISOString().slice(0,10);document.getElementById('tx-account').innerHTML='<option value="">Select account</option>'+accounts.map(a=>`<option value="${a.id}">${esc(a.name)}</option>`).join('');modal.classList.add('open');document.getElementById('tx-desc').focus();}
document.getElementById('quick-add').onclick=openTransaction;document.getElementById('transaction-add').onclick=openTransaction;document.getElementById('close-modal').onclick=()=>modal.classList.remove('open');modal.onclick=e=>{if(e.target===modal)modal.classList.remove('open')};
document.querySelector('.modal').addEventListener('submit',async e=>{e.preventDefault();try{const amount=Number(document.getElementById('tx-amount').value)*(document.getElementById('tx-type').value==='expense'?-1:1);const categoryName=document.getElementById('tx-category').value;let category=categories.find(c=>c.name===categoryName);if(!category){category=await pb.collection('categories').create({user:pb.authStore.record.id,name:categoryName,group:amount>0?'income':'wants'});categories.push(category)}const record=await pb.collection('transactions').create({user:pb.authStore.record.id,merchant:document.getElementById('tx-desc').value,amount,date:new Date(document.getElementById('tx-date').value+'T12:00:00').toISOString(),kind:amount>0?'income':'expense',category:category.id,account:document.getElementById('tx-account').value||null});transactions.unshift(record);renderAll();modal.classList.remove('open');e.target.reset();toast('Transaction saved to PocketBase');}catch(err){toast(err.message||'Could not save transaction',true)}});

const createSchemas={
  accounts:{title:'Add account',fields:[['name','Account name'],['type','Type (checking, savings, credit_card, retirement, brokerage)'],['institution','Institution'],['balance','Current balance','number']]},
  monthly_budgets:{title:'Add budget category',fields:[['category','Category name'],['planned_amount','Monthly amount','number']]},
  debts:{title:'Add loan or debt',fields:[['name','Name'],['debt_type','Type (mortgage, student_loan, auto_loan, credit_card)'],['current_balance','Current balance','number'],['interest_rate','APR %','number'],['minimum_payment','Monthly payment','number']]},
  recurring_items:{title:'Add recurring bill',fields:[['name','Bill name'],['amount','Amount','number'],['frequency','Frequency (monthly, weekly, yearly)'],['next_due_date','Next due date','date']]},
  investment_accounts:{title:'Add investment account',fields:[['name','Account name'],['account_type','Type (401k, roth_ira, brokerage, hsa)'],['current_value','Current value','number'],['monthly_contribution','Monthly contribution','number']]},
  goals:{title:'Add savings goal',fields:[['name','Goal name'],['target_amount','Target amount','number'],['current_amount','Current amount','number'],['monthly_contribution','Monthly contribution','number']]},
  scenarios:{title:'Save scenario',fields:[['name','Scenario name'],['purchase_amount','Purchase amount','number']]}
};
function bindCreateButtons(){document.querySelectorAll('[data-create]').forEach(b=>b.onclick=()=>openCreator(b.dataset.create));document.querySelectorAll('.page .add-button').forEach(b=>{const page=b.closest('.page')?.id;if(b.id||b.dataset.bound)return;b.dataset.bound='1';const map={budget:'monthly_budgets',loans:'debts',investments:'investment_accounts',bills:'recurring_items'};if(map[page])b.onclick=()=>openCreator(map[page])});document.querySelector('#budget .outline-btn').onclick=()=>openCreator('monthly_budgets')}
function openCreator(type){const schema=createSchemas[type];if(!schema)return;const fields=schema.fields.map(([key,label,input='text'])=>`<label>${label}<input name="${key}" type="${input}" required></label>`).join('');const overlay=document.createElement('div');overlay.className='modal-backdrop open';overlay.innerHTML=`<form class="modal"><button type="button" class="modal-close">×</button><p class="eyebrow">POCKETBASE</p><h2>${schema.title}</h2>${fields}<button class="add-button" type="submit">Save</button></form>`;document.body.append(overlay);overlay.querySelector('.modal-close').onclick=()=>overlay.remove();overlay.onclick=e=>{if(e.target===overlay)overlay.remove()};overlay.querySelector('form').onsubmit=async e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.target));for(const [k,v] of Object.entries(data))if(e.target.elements[k].type==='number')data[k]=Number(v);try{if(type==='monthly_budgets'){let c=categories.find(x=>x.name===data.category);if(!c){c=await pb.collection('categories').create({user:pb.authStore.record.id,name:data.category,group:'needs'});categories.push(c)}data.category=c.id;data.month=new Date(new Date().getFullYear(),new Date().getMonth(),1).toISOString()}data.user=pb.authStore.record.id;await pb.collection(type).create(data);overlay.remove();await loadData();toast('Saved to PocketBase')}catch(err){toast(err.message||'Could not save',true)}}}

function updateScenario(){const price=Number(document.getElementById('scenario-price').value||0),income=transactions.filter(t=>t.amount>0).reduce((s,t)=>s+t.amount,0),spend=Math.abs(transactions.filter(t=>t.amount<0).reduce((s,t)=>s+t.amount,0)),left=income-spend-price;document.getElementById('scenario-result').textContent=money.format(left);document.getElementById('scenario-summary').textContent=`after buying ${document.getElementById('scenario-name').value||'this'}`;document.getElementById('goal-impact').textContent=price>1500?'Delayed 3 months':'Delayed 2 months';document.getElementById('cushion-impact').textContent=`${Math.max(0,Math.round(left/58))} days`;document.getElementById('scenario-saved').textContent=`${money.format(Math.max(0,left*6))} saved`;document.getElementById('scenario-bar').style.width=`${Math.max(12,Math.min(86,left/2000*86))}%`;}
document.getElementById('scenario-price').addEventListener('input',updateScenario);document.getElementById('scenario-name').addEventListener('input',updateScenario);document.querySelector('#scenario .outline-btn').onclick=()=>openCreator('scenarios');
document.querySelectorAll('.month-toggle button').forEach((b,i)=>b.onclick=()=>{displayedMonth=new Date(displayedMonth.getFullYear(),displayedMonth.getMonth()+(i?1:-1),1);renderDashboard();toast(`Showing ${displayedMonth.toLocaleDateString('en-US',{month:'long',year:'numeric'})}`)});
document.querySelector('.workspace').onclick=()=>{const current=localStorage.getItem('northstar-workspace')||`${pb.authStore.record?.name||'My'}’s finances`;const next=prompt('Name this financial workspace:',current);if(next?.trim()){localStorage.setItem('northstar-workspace',next.trim());document.querySelector('.workspace').childNodes[1].textContent=next.trim();toast('Workspace name updated')}};
const iconButtons=document.querySelectorAll('.top-actions .icon-btn');iconButtons[0].onclick=()=>{const term=prompt('Search transactions, bills, and accounts:');if(!term)return;const q=term.toLowerCase(),matches=transactions.filter(t=>`${t.merchant} ${t.description}`.toLowerCase().includes(q));showPage('transactions');transactionFilter='all';renderTransactions();toast(matches.length?`${matches.length} matching transaction${matches.length===1?'':'s'} shown below`:'No matching saved transactions')};iconButtons[1].onclick=()=>toast(recurring.length?`${recurring.length} recurring bill${recurring.length===1?'':'s'} are being tracked.`:'No new notifications.');
document.querySelectorAll('.dots').forEach(b=>b.onclick=()=>toast('Card options: your data is saved automatically in PocketBase.'));
document.querySelectorAll('.filter').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');const label=b.textContent.trim().toLowerCase();transactionFilter=label.includes('income')?'income':label.includes('expense')?'expense':label.includes('transfer')?'transfer':'all';renderTransactions()}));

function authScreen(){const screen=document.createElement('div');screen.id='auth-screen';screen.innerHTML=`<form class="auth-card"><div class="brand"><span class="brand-mark">N</span><span>northstar</span></div><p class="eyebrow">YOUR PRIVATE MONEY SPACE</p><h1>Welcome back.</h1><p>Sign in to securely access your finances.</p><label>Email<input name="email" type="email" required autocomplete="email"></label><label>Password<input name="password" type="password" required autocomplete="current-password"></label><button class="add-button" type="submit">Sign in</button><button type="button" class="text-btn" id="show-signup">Create an account</button><small id="auth-message"></small></form>`;document.body.append(screen);screen.querySelector('form').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target);try{await pb.collection('users').authWithPassword(f.get('email'),f.get('password'));screen.remove();await loadData();toast('Signed in securely')}catch(err){screen.querySelector('#auth-message').textContent=err.message||'Sign-in failed'}};screen.querySelector('#show-signup').onclick=()=>{screen.querySelector('.auth-card').innerHTML=`<div class="brand"><span class="brand-mark">N</span><span>northstar</span></div><p class="eyebrow">GET STARTED</p><h1>Create your account.</h1><label>Name<input name="name" required></label><label>Email<input name="email" type="email" required></label><label>Password<input name="password" type="password" minlength="8" required></label><label>Confirm password<input name="passwordConfirm" type="password" minlength="8" required></label><button class="add-button" type="submit">Create account</button><small id="auth-message"></small>`;screen.querySelector('form').onsubmit=async e=>{e.preventDefault();try{const data=Object.fromEntries(new FormData(e.target));await pb.collection('users').create(data);await pb.collection('users').authWithPassword(data.email,data.password);screen.remove();await loadData();toast('Account created')}catch(err){screen.querySelector('#auth-message').textContent=err.message||'Could not create account'}}}}
if(pb.authStore.isValid)loadData().then(updateScenario);else authScreen();
