(()=>{'use strict';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
if(!window.THREE){$('#loading').classList.add('hidden');$('#error').classList.remove('hidden');return}

const SAVE_KEY='northwoods_after_dark_save_v1';
const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(70,innerWidth/innerHeight,.1,900);
const renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});
renderer.setSize(innerWidth,innerHeight);renderer.setPixelRatio(Math.min(devicePixelRatio,1.7));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.08;renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;$('#game').appendChild(renderer.domElement);
const worldGroup=new THREE.Group(),dynamicGroup=new THREE.Group(),interiorGroup=new THREE.Group(),mineGroup=new THREE.Group(),ruinGroup=new THREE.Group();interiorGroup.visible=false;mineGroup.visible=false;ruinGroup.visible=false;scene.add(worldGroup,dynamicGroup,interiorGroup,mineGroup,ruinGroup);camera.rotation.order='YXZ';

const state={running:false,paused:true,dead:false,ending:false,locked:false,interior:false,interiorMode:null,currentRuin:null,cutscene:false,quest:0,day:1,minutes:18*60+42,weather:'CLEAR',weatherTimer:150,health:100,stamina:100,warmth:88,hunger:92,ammo:6,reserve:18,slot:1,flashlight:false,location:'KELLEY CABIN',shots:0,fishCaught:0,deerHunted:0,woodCut:0,startTime:0,inventory:{knife:1,flashlight:1,rifle:1,axe:1,ammo:18,wood:2,matches:1,food:2,bandage:1},discovered:['cabin'],flags:{truckLooted:false,generator:false,tower:false,note:false,campfire:false,cabinLooted:false,ending:false,chapter1:false,serviceLooted:false,shackLooted:false,boathouseLooted:false,garageLooted:false,trapperLooted:false,shelterLooted:false,ruinLoot:{},truckReady:false,cleansed:false},player:{x:0,z:9,yaw:Math.PI,pitch:0},exterior:{x:0,z:9}};
const itemDefs={knife:['FIELD KNIFE','Reliable, sharp, and older than it looks.','🗡️'],flashlight:['FLASHLIGHT','A steel-bodied light. The batteries are somehow still good.','🔦'],rifle:['.30-30 RIFLE','A lever-action deer rifle. Six rounds loaded.','▱'],axe:['CAMP AXE','Splits firewood and solves other problems.','🪓'],ammo:['.30-30 ROUNDS','Ammunition for the rifle.','▤'],wood:['DRY FIREWOOD','Enough to keep a fire going for a while.','▥'],matches:['WATERPROOF MATCHES','An old orange box of strike-anywhere matches.','▨'],food:['CANNED STEW','Cold, heavy, and filling.','🥫'],bandage:['FIELD DRESSING','Restores 30 health.','✚'],fuel:['GAS CAN','Enough gasoline to wake an engine—or burn something buried.','⛽'],fuse:['15A GLASS FUSE','The ranger tower radio needs this.','⌁'],battery:['TRUCK BATTERY','Heavy, charged, and almost the right size.','▣'],belt:['FAN BELT','Old rubber, no cracks. It should hold.','◉'],plugs:['SPARK PLUG SET','Four clean plugs in an oil-stained box.','⚡'],fish:['WALLEYE','Fresh Cedar Lake walleye. Restores hunger when cooked.','🐟'],venison:['VENISON','Fresh meat. Better cooked over a fire.','🥩'],scrap:['ELECTRICAL SCRAP','Wire, contacts, and a surprisingly clean relay.','⚙']};
const questData=[['COLD START','Search the truck for the generator fuel.'],['LIGHTS ON','Fuel the generator behind the cabin.'],['DEAD AIR','Search the Old Campground supply crate for a 15A fuse, then repair the ranger tower radio.'],['COME HOME','Get back inside the cabin. Do not stop in the trees.'],['THE ANSWER','Use the radio inside the cabin.'],['TWO WAYS OUT','Repair the truck for a fast escape—or enter the mine and end what lives below.'],['ROAD REPAIR','Find a battery, fan belt, spark plugs, and fuel. Check the marked sites.'],['LAST DRIVE','All four parts are ready. Return to the truck and get out.'],['THE ROOT BELOW','Carry gasoline and matches into the mine. Reach the buried heart.'],['THE WOODS ARE QUIET','The source is gone. Cedar Lake is safe to explore.']];
const POIS={cabin:{x:0,z:0,label:'Kelley Cabin'},dock:{x:34,z:-28,label:'Fishing Dock'},camp:{x:82,z:35,label:'Old Campground'},tower:{x:-76,z:-94,label:'Ranger Tower'},mine:{x:108,z:78,label:'Abandoned Mine'},lookout:{x:-112,z:54,label:'Fire Lookout'},service:{x:-142,z:-32,label:'North Point Service Shed'},shack:{x:122,z:-112,label:'Collapsed Hunting Shack'},boathouse:{x:116,z:-56,label:'Old Boathouse'},garage:{x:-45,z:118,label:'County Maintenance Garage'},trapper:{x:155,z:42,label:'Abandoned Trapper Cabin'},shelter:{x:-132,z:105,label:'Storm Shelter'},lake:{x:55,z:-58,label:'Cedar Lake'}};
const RUIN_LOOT={service:{shelf:{scrap:3,matches:1},desk:{ammo:5,bandage:1},locker:{food:1,wood:2}},shack:{shelf:{wood:3,matches:2},desk:{scrap:1,ammo:4},locker:{food:2,bandage:1}},boathouse:{shelf:{scrap:2,wood:2},desk:{matches:2,ammo:5},locker:{food:1,bandage:1}},garage:{shelf:{scrap:4,wood:1},desk:{matches:2,ammo:8},locker:{bandage:2,food:1}},trapper:{shelf:{wood:4,matches:2},desk:{ammo:6,scrap:1},locker:{food:3,bandage:1}},shelter:{shelf:{scrap:3,matches:3},desk:{ammo:10,bandage:1},locker:{food:2,wood:2}}};
const interactables=[],animals=[],enemies=[],campfires=[],particles=[],trees=[],colliders=[],interiorColliders=[],mineColliders=[],ruinColliders=[],interiorLights=[];let activeInteract=null,selectedInv='knife',messageTimer=0,autosaveTimer=0,footTimer=0,reloadTimer=0,threatLevel=0,fishTimer=null,fishPhase='idle',truckGroup=null,truckCutsceneTime=0;
const keys={},moveVec=new THREE.Vector3(),velocity=new THREE.Vector3(),raycaster=new THREE.Raycaster(),clock=new THREE.Clock(),up=new THREE.Vector3(0,1,0),tmp=new THREE.Vector3();
let sun,moon,hemi,ambient,flashlight,rain,stars,water,audio,master,windOsc,droneGain;

function clamp(v,a,b){return Math.max(a,Math.min(b,v))}function lerp(a,b,t){return a+(b-a)*t}function dist2(x,z,x2,z2){return Math.hypot(x-x2,z-z2)}
function heightAt(x,z){const lakeD=dist2(x,z,55,-58);let h=4+Math.sin(x*.035)*1.8+Math.cos(z*.042)*1.35+Math.sin((x+z)*.018)*2.2+Math.sin(x*.11+z*.06)*.45;if(lakeD<50)return-2.2;if(lakeD<64)h=lerp(-2.2,h,(lakeD-50)/14);const flats=[[0,0,24,4],[-76,-94,14,4.5],[82,35,13,5],[108,78,12,5],[-142,-32,13,4],[122,-112,13,4],[116,-56,13,1],[-45,118,13,5],[155,42,13,4],[-132,105,13,5]];for(const [fx,fz,r,fy] of flats){const d=dist2(x,z,fx,fz);if(d<r)h=lerp(fy,h,d/r)}return h}
function material(color,rough=.8,metal=.02,emissive=0,intensity=0){return new THREE.MeshStandardMaterial({color,roughness:rough,metalness:metal,emissive,emissiveIntensity:intensity})}
function mesh(geo,mat,x=0,y=0,z=0,parent=worldGroup){const m=new THREE.Mesh(geo,mat);m.position.set(x,y,z);m.castShadow=true;m.receiveShadow=true;parent.add(m);return m}
function box(w,h,d,c,x,y,z,parent=worldGroup,rough=.8,metal=.02){return mesh(new THREE.BoxGeometry(w,h,d),material(c,rough,metal),x,y,z,parent)}
function addInteract(obj,label,range,action,zone='outside'){const it={obj,label,range,action,zone};interactables.push(it);obj.userData.interact=it;return it}
function addCollider(x,z,hx,hz,zone='outside'){(zone==='mine'?mineColliders:zone==='ruin'?ruinColliders:zone==='inside'?interiorColliders:colliders).push({x,z,hx,hz})}
function hitsCollider(x,z){const list=state.interiorMode==='mine'?mineColliders:state.interiorMode==='ruin'?ruinColliders:state.interior?interiorColliders:colliders;if(!state.interior&&trees.some(t=>dist2(x,z,t.x,t.z)<t.r*.72))return true;return list.some(c=>x>c.x-c.hx&&x<c.x+c.hx&&z>c.z-c.hz&&z<c.z+c.hz)}

function buildTerrain(){
  const size=420,seg=150,g=new THREE.PlaneGeometry(size,size,seg,seg),p=g.attributes.position;for(let i=0;i<p.count;i++)p.setZ(i,heightAt(p.getX(i),-p.getY(i)));g.computeVertexNormals();const land=mesh(g,material(0x263a25,.96));land.rotation.x=-Math.PI/2;land.receiveShadow=true;
  water=mesh(new THREE.CircleGeometry(52,72),new THREE.MeshPhysicalMaterial({color:0x173b3b,roughness:.18,metalness:.05,transparent:true,opacity:.84,transmission:.12}),55,-.25,-58);water.rotation.x=-Math.PI/2;water.receiveShadow=true;
  const shore=mesh(new THREE.RingGeometry(48,66,72),material(0x766849,1),55,.02,-58);shore.rotation.x=-Math.PI/2;
  const roadMat=material(0x473d2c,1);for(let i=-110;i<85;i++){const z=20-i*1.55,x=-3-Math.sin(i*.13)*10;const r=mesh(new THREE.PlaneGeometry(6.5,2.2),roadMat,x,heightAt(x,z)+.035,z);r.rotation.x=-Math.PI/2;r.rotation.z=Math.sin(i*.13)*-.07;r.receiveShadow=true}
}
function buildSky(){
  scene.background=new THREE.Color(0x334b42);scene.fog=new THREE.FogExp2(0x425149,.008);hemi=new THREE.HemisphereLight(0xbad4ca,0x11130d,1.35);scene.add(hemi);ambient=new THREE.AmbientLight(0x849488,.4);scene.add(ambient);sun=new THREE.DirectionalLight(0xffd3a0,2.4);sun.castShadow=true;sun.shadow.mapSize.set(1536,1536);sun.shadow.camera.left=-100;sun.shadow.camera.right=100;sun.shadow.camera.top=100;sun.shadow.camera.bottom=-100;scene.add(sun);moon=new THREE.DirectionalLight(0x8aa7d8,.4);scene.add(moon);
  const sg=new THREE.BufferGeometry(),a=new Float32Array(1600*3);for(let i=0;i<1600;i++){const r=350,u=Math.random()*Math.PI*2,v=Math.acos(Math.random());a[i*3]=Math.sin(v)*Math.cos(u)*r;a[i*3+1]=Math.cos(v)*r;a[i*3+2]=Math.sin(v)*Math.sin(u)*r}sg.setAttribute('position',new THREE.BufferAttribute(a,3));stars=new THREE.Points(sg,new THREE.PointsMaterial({color:0xdbe8ff,size:.7,transparent:true,opacity:0}));scene.add(stars);
  const rg=new THREE.BufferGeometry(),ra=new Float32Array(800*3);for(let i=0;i<800;i++){ra[i*3]=(Math.random()-.5)*180;ra[i*3+1]=Math.random()*70;ra[i*3+2]=(Math.random()-.5)*180}rg.setAttribute('position',new THREE.BufferAttribute(ra,3));rain=new THREE.Points(rg,new THREE.PointsMaterial({color:0xb8d7df,size:.12,transparent:true,opacity:0}));scene.add(rain);
  flashlight=new THREE.SpotLight(0xfff1cf,0,78,Math.PI/5.4,.34,1.2);flashlight.position.set(.25,-.1,0);flashlight.target.position.set(0,-.4,-18);camera.add(flashlight,flashlight.target);
}
function pine(x,z,s=1){const y=heightAt(x,z),g=new THREE.Group();g.position.set(x,y,z);const trunk=mesh(new THREE.CylinderGeometry(.18*s,.28*s,3.8*s,6),material(0x4a3525,.95),0,1.9*s,0,g);for(let j=0;j<3;j++){const crown=mesh(new THREE.ConeGeometry((1.9-j*.36)*s,4.1*s,7),material(j?0x173321:0x1d4329,.95),0,(3.8+j*1.45)*s,0,g);crown.rotation.y=Math.random()*2}worldGroup.add(g);trees.push({x,z,r:1.1*s,g});return g}
function birch(x,z,s=1){const y=heightAt(x,z),g=new THREE.Group();g.position.set(x,y,z);mesh(new THREE.CylinderGeometry(.13*s,.18*s,5*s,6),material(0xb6b39c,.9),0,2.5*s,0,g);for(let j=0;j<3;j++){const c=mesh(new THREE.IcosahedronGeometry(1.2*s,0),material(0x5f7036,.95),Math.sin(j*2)*.7*s,(5+j*.4)*s,Math.cos(j*2)*.7*s,g);c.scale.y=.8}worldGroup.add(g);trees.push({x,z,r:.8*s,g})}
function buildForest(){let made=0,tries=0;while(made<470&&tries++<2000){const x=(Math.random()-.5)*390,z=(Math.random()-.5)*390;if(dist2(x,z,55,-58)<68||dist2(x,z,0,0)<27||dist2(x,z,-76,-94)<18||dist2(x,z,82,35)<18||dist2(x,z,108,78)<16||dist2(x,z,-142,-32)<14||dist2(x,z,122,-112)<14||dist2(x,z,116,-56)<14||dist2(x,z,-45,118)<14||dist2(x,z,155,42)<14||dist2(x,z,-132,105)<14)continue;if(Math.random()<.13)birch(x,z,.7+Math.random()*.55);else pine(x,z,.72+Math.random()*.75);made++}for(let i=0;i<90;i++){const x=(Math.random()-.5)*380,z=(Math.random()-.5)*380;if(heightAt(x,z)<0)continue;const size=.25+Math.random()*1.1,r=mesh(new THREE.DodecahedronGeometry(size,0),material(0x343b31,1),x,heightAt(x,z)+size*.35,z);r.rotation.set(Math.random()*3,Math.random()*3,Math.random()*3);if(size>.55)addCollider(x,z,size*.72,size*.72)}}
function buildCabin(){const x=0,z=0,y=heightAt(x,z);const g=new THREE.Group();g.position.set(x,y,z);box(11,5.5,8,0x4a3324,0,2.75,0,g);const roof=mesh(new THREE.ConeGeometry(7.5,3,4),material(0x22231f,.98),0,7,0,g);roof.rotation.y=Math.PI/4;roof.scale.z=.78;const door=box(1.8,3.4,.15,0x20150f,0,1.7,4.08,g);box(2.4,1.8,.12,0x7894a0,-3,3.2,4.1,g,0,.15);box(2.4,1.8,.12,0x7894a0,3,3.2,4.1,g,0,.15);box(12,.35,3,0x543d2b,0,.15,5,g);for(let sx of[-5,5])box(.2,2.5,.2,0x634932,sx,1.25,5.8,g);worldGroup.add(g);addCollider(0,0,5.7,4.15);addInteract(door,'ENTER CABIN',3.2,()=>enterCabin());
  const gen=new THREE.Group();gen.position.set(-8,heightAt(-8,4),4);box(2,1.25,1.4,0x3a4938,0,.65,0,gen,.35,.55);box(.4,.5,.1,0xa73724,.45,.75,.72,gen);worldGroup.add(gen);addCollider(-8,4,1.15,.82);addInteract(gen,'INSPECT GENERATOR',3,()=>useGenerator());
  const fire=new THREE.Group();fire.position.set(7,heightAt(7,8),8);for(let i=0;i<8;i++){const a=i/8*Math.PI*2;mesh(new THREE.DodecahedronGeometry(.35,0),material(0x6b6655,1),Math.cos(a)*1,.25,Math.sin(a)*1,fire)}const flame=mesh(new THREE.ConeGeometry(.42,1.25,7),material(0xff6b24,.25,0,0xff3b12,4),0,.75,0,fire);flame.visible=false;const glow=new THREE.PointLight(0xff8a3c,0,30,1.5);glow.position.y=1.4;fire.add(glow);worldGroup.add(fire);const cf={g:fire,glow,flames:[flame],lit:false};campfires.push(cf);addInteract(fire,'LIGHT CAMPFIRE',3,()=>lightFire(cf));
  const note=box(.75,.035,.55,0xd3c49a,-1.7,y+.39,5.15,worldGroup,1,0);note.rotation.y=-.2;addInteract(note,'READ FOLDED NOTE',2.5,()=>{state.flags.note=true;openNote('OCTOBER 17','Justin—',`I drove into town for supplies. The ranger station called twice while you were out. Both times there was only breathing on the line.\n\nThere is gas in the truck if the generator dies again. Please lock the door before dark.\n\n— B.`)});
}
function buildTruck(){const x=15,z=8,y=heightAt(x,z);const g=new THREE.Group();truckGroup=g;g.position.set(x,y,z);box(6,1.4,3,0x2f4a3a,0,1.25,0,g,.5,.45);box(2.9,1.6,2.7,0x263b31,-1,2.45,0,g,.55,.5);for(let sx of[-2.1,2.1])for(let sz of[-1.48,1.48]){const w=mesh(new THREE.CylinderGeometry(.55,.55,.35,12),material(0x10110f,.9),sx,.6,sz,g);w.rotation.x=Math.PI/2}box(1.6,.75,.05,0x799198,-1.1,2.55,1.38,g,.15,.2);worldGroup.add(g);addCollider(x,z,3.2,1.75);addInteract(g,'INSPECT TRUCK',4,()=>handleTruck())}
function buildDock(){const x=34,z=-28,y=heightAt(x,z);for(let i=0;i<11;i++)box(3.8,.25,2,0x594331,x+i*2.4,y+i*-.13,z-i*2.05);const spot=new THREE.Group();spot.position.set(55,.1,-49);worldGroup.add(spot);addInteract(spot,'FISH CEDAR LAKE',5,()=>startFishing());POIS.dock.y=y}
function buildCamp(){const x=82,z=35,y=heightAt(x,z);for(let i=0;i<3;i++){const tx=x+i*8-8,tz=z+(i%2)*5,t=mesh(new THREE.ConeGeometry(3,3,4),material(0x6a5635,.95),tx,y+1.5,tz);t.rotation.y=Math.PI/4;addCollider(tx,tz,2.4,2.4)}const fire=new THREE.Group();fire.position.set(x,y,z+8);for(let i=0;i<7;i++){const a=i/7*6.28;mesh(new THREE.DodecahedronGeometry(.32),material(0x5d5a4d),Math.cos(a),.2,Math.sin(a),fire)}const flame=mesh(new THREE.ConeGeometry(.42,1.25,7),material(0xff6b24,.25,0,0xff3b12,4),0,.75,0,fire);flame.visible=false;const glow=new THREE.PointLight(0xff8a3c,0,30,1.5);glow.position.y=1.4;fire.add(glow);worldGroup.add(fire);const cf={g:fire,glow,flames:[flame],lit:false};campfires.push(cf);addInteract(fire,'LIGHT CAMPGROUND FIRE',3,()=>lightFire(cf));const crate=box(2,1.2,1.4,0x4c3d29,x+6,y+.6,z+4);addCollider(x+6,z+4,1.1,.8);addInteract(crate,'LOOT RANGER SUPPLY CRATE',3,()=>{if(crate.userData.looted)return showMessage('The crate is empty.');crate.userData.looted=true;addItem('ammo',6);addItem('food',2);addItem('bandage',1);addItem('fuse',1);discover('camp');showMessage('FOUND: 15A FUSE, AMMO, STEW, FIELD DRESSING')})}
function buildTower(){const x=-76,z=-94,y=heightAt(x,z);for(let sx of[-3,3])for(let sz of[-3,3]){const leg=mesh(new THREE.CylinderGeometry(.13,.22,22,6),material(0x4c524c,.55,.8),x+sx,y+11,z+sz);leg.rotation.z=sx*.012;leg.rotation.x=sz*.012}for(let h=3;h<22;h+=3){box(7,.12,.12,0x555e58,x,y+h,z);box(.12,.12,7,0x555e58,x,y+h,z)}box(7,4.5,7,0x3e493f,x,y+23,z);box(2.3,1.5,.05,0x71868b,x,y+23.7,z+3.52,worldGroup,.18,.1);const radio=new THREE.Group();radio.position.set(x,y+2,z+4.2);worldGroup.add(radio);addCollider(x,z,3.35,3.35);addInteract(radio,state.flags.tower?'LISTEN TO REPAIRED RADIO':'REPAIR TOWER RADIO',4,()=>repairTower());const beacon=new THREE.PointLight(0xd34731,2.5,35);beacon.position.set(x,y+27,z);worldGroup.add(beacon);particles.push({type:'beacon',obj:beacon});POIS.tower.y=y}
function buildMine(){const x=108,z=78,y=heightAt(x,z);const mouth=mesh(new THREE.TorusGeometry(5,1.1,8,12,Math.PI),material(0x32352f,1),x,y,z);mouth.rotation.x=Math.PI/2;mouth.rotation.z=Math.PI;const dark=mesh(new THREE.CircleGeometry(4.7,24),new THREE.MeshBasicMaterial({color:0x000000}),x,y+1,z-.1);addCollider(x,z,4.5,1.3);addInteract(dark,'ENTER ABANDONED MINE',5,()=>{if(state.quest<5&&!state.flags.chapter1)return showMessage('The boards will not move. Something scratches behind them.');enterMine()});for(let i=-2;i<=2;i++)box(.3,7,.3,0x503824,x+i*2,y+3.5,z+.2)}
function buildSalvageSites(){
  const sites=[
    {id:'service',x:-142,z:-32,c:0x37463b,flag:'serviceLooted',outside:{battery:1,ammo:10,fuel:1}},
    {id:'shack',x:122,z:-112,c:0x4b3828,flag:'shackLooted',outside:{belt:1,ammo:8,fuel:1}},
    {id:'boathouse',x:116,z:-56,c:0x34444a,flag:'boathouseLooted',outside:{plugs:1,ammo:12,fuel:1}},
    {id:'garage',x:-45,z:118,c:0x3e4540,flag:'garageLooted',outside:{fuel:1,ammo:6,scrap:1}},
    {id:'trapper',x:155,z:42,c:0x55402d,flag:'trapperLooted',outside:{fuel:1,wood:3,food:1}},
    {id:'shelter',x:-132,z:105,c:0x404641,flag:'shelterLooted',outside:{fuel:1,ammo:5,bandage:1}}
  ];
  for(const s of sites){const y=heightAt(s.x,s.z),g=new THREE.Group();g.position.set(s.x,y,s.z);box(8,3.6,6,s.c,0,1.8,0,g);const roof=mesh(new THREE.ConeGeometry(5.5,2,4),material(0x252722,.98),0,4.5,0,g);roof.rotation.y=Math.PI/4;roof.scale.z=.8;const door=box(2,2.8,.12,0x171812,0,1.4,3.05,g);worldGroup.add(g);addCollider(s.x,s.z,4.2,3.2);addInteract(door,`ENTER ${POIS[s.id].label.toUpperCase()}`,4.2,()=>enterRuin(s.id));const crate=box(1.8,1.1,1.25,0x5a482e,s.x+5,y+.55,s.z+1);addCollider(s.x+5,s.z+1,1,.75);addInteract(crate,'SEARCH OUTDOOR SUPPLY CACHE',3,()=>{if(state.flags[s.flag])return showMessage('The outdoor cache is empty.');state.flags[s.flag]=true;grantLoot(s.outside);discover(s.id);checkTruckParts();saveGame()})}
}
function grantLoot(loot){const found=[];for(const [id,n] of Object.entries(loot)){addItem(id,n);found.push(`${n} ${itemDefs[id]?.[0]||id.toUpperCase()}`)}showMessage(`FOUND: ${found.join(' · ')}`,4200)}
function buildRuinInterior(){
  box(11,.3,9,0x363832,0,-.15,0,ruinGroup);box(11,4.2,.3,0x292b27,0,2.1,-4.5,ruinGroup);box(.3,4.2,9,0x292b27,-5.5,2.1,0,ruinGroup);box(.3,4.2,9,0x292b27,5.5,2.1,0,ruinGroup);box(4.4,4.2,.3,0x292b27,-3.3,2.1,4.5,ruinGroup);box(4.4,4.2,.3,0x292b27,3.3,2.1,4.5,ruinGroup);box(11,.35,9,0x1b1d1a,0,4.25,0,ruinGroup);
  const exit=box(2.1,3.5,.18,0x171812,0,1.75,4.38,ruinGroup);addInteract(exit,'LEAVE BUILDING',2.7,()=>exitRuin(),'ruin');
  const shelf=new THREE.Group();shelf.position.set(-4.25,0,-1.7);for(const y of[.4,1.35,2.3])box(1.8,.12,1.2,0x58432e,0,y,0,shelf);for(const x of[-.78,.78])box(.12,2.7,.12,0x493724,x,1.35,0,shelf);ruinGroup.add(shelf);addCollider(-4.25,-1.7,1.05,.75,'ruin');addInteract(shelf,'SEARCH DUSTY SHELVES',2.8,()=>searchRuin('shelf'),'ruin');
  const desk=new THREE.Group();desk.position.set(.3,0,-3.35);box(3,.25,1.35,0x5d452f,0,1,0,desk);for(const x of[-1.2,1.2])box(.15,1,.15,0x493623,x,.5,0,desk);ruinGroup.add(desk);addCollider(.3,-3.35,1.65,.8,'ruin');addInteract(desk,'SEARCH ABANDONED DESK',2.8,()=>searchRuin('desk'),'ruin');
  const locker=box(1.7,3.1,1.1,0x3f4a43,4.25,1.55,1.5,ruinGroup,.45,.45);addCollider(4.25,1.5,1,.7,'ruin');addInteract(locker,'SEARCH RUSTED LOCKER',2.8,()=>searchRuin('locker'),'ruin');
  const lamp=new THREE.PointLight(0xffb46b,2.1,18,1.8);lamp.position.set(0,3.5,.5);ruinGroup.add(lamp);
}
function buildMineInterior(){
  box(15,.35,50,0x292b27,0,-.18,-17,mineGroup);box(.8,5.5,50,0x20231f,-7.2,2.7,-17,mineGroup);box(.8,5.5,50,0x20231f,7.2,2.7,-17,mineGroup);box(15,.6,50,0x171916,0,5.4,-17,mineGroup);
  for(let z=4;z>-40;z-=6){for(const x of[-5.7,5.7])box(.35,5,.35,0x4c3928,x,2.5,z,mineGroup);box(11.8,.35,.35,0x4c3928,0,4.85,z,mineGroup)}
  const exit=box(3.1,4.2,.2,0x10110f,0,2.1,7.65,mineGroup);addInteract(exit,'LEAVE THE MINE',3,()=>exitMine(),'mine');
  const altar=new THREE.Group();altar.position.set(0,0,-39);box(5,1.2,3,0x353632,0,.6,0,altar);const heart=mesh(new THREE.IcosahedronGeometry(1.25,1),material(0x35100f,.4,.1,0x8b100d,3.5),0,2.05,0,altar);heart.scale.y=1.4;const glow=new THREE.PointLight(0xd21f17,7,24,1.4);glow.position.set(0,2.2,0);altar.add(glow);mineGroup.add(altar);particles.push({type:'heart',obj:heart,glow});addInteract(altar,'BURN THE BURIED HEART',3.4,()=>destroyHeart(),'mine');
  for(const z of[1,-13,-27,-37]){const lamp=new THREE.PointLight(0xffa552,2.8,13,1.7);lamp.position.set((z%2)*2,3.4,z);mineGroup.add(lamp)}
  const cache=box(1.6,1,1.2,0x55432d,4.8,.5,-20,mineGroup);addInteract(cache,'OPEN MINER CACHE',2.8,()=>{if(cache.userData.looted)return showMessage('The cache is empty.');cache.userData.looted=true;addItem('ammo',12);addItem('bandage',2);showMessage('FOUND: 12 ROUNDS + 2 FIELD DRESSINGS')},'mine');
}
function buildLookout(){const x=-112,z=54,y=heightAt(x,z);box(8,.5,8,0x453825,x,y+.25,z);for(let sx of[-3.4,3.4])for(let sz of[-3.4,3.4])box(.35,5,.35,0x4e3d2a,x+sx,y+2.5,z+sz);const note=box(.8,.06,.6,0xd3c49a,x,y+.58,z);addInteract(note,'READ WEATHERED JOURNAL',3,()=>openNote('OCTOBER 14','I saw it again.',`Across the lake. Too tall for a man. Too thin for a bear.\n\nIt only moves when the tower light goes out. Ranger Cole says I need sleep. Cole has not answered the radio in two days.\n\nIf someone finds this: do not follow the whistling.`));}
function buildInterior(){
  box(10,.3,7.8,0x493525,0,-.15,0,interiorGroup);box(10,3.6,.3,0x39291f,0,1.8,-3.9,interiorGroup);box(.3,3.6,7.8,0x39291f,-5,1.8,0,interiorGroup);box(.3,3.6,7.8,0x39291f,5,1.8,0,interiorGroup);box(4.1,3.6,.3,0x39291f,-3,1.8,3.9,interiorGroup);box(4.1,3.6,.3,0x39291f,3,1.8,3.9,interiorGroup);box(10,.25,7.8,0x211a15,0,3.7,0,interiorGroup);
  const exit=box(1.8,3.25,.18,0x211611,0,1.62,3.78,interiorGroup);addInteract(exit,'EXIT CABIN',2.4,()=>exitCabin(),'inside');
  const bed=new THREE.Group();bed.position.set(3.25,0,-2.15);box(3.1,.55,1.75,0x463628,0,.42,0,bed);box(2.85,.3,1.55,0x7d4038,0,.83,0,bed);box(.75,.22,1.35,0xd0c3a3,-.88,1.03,0,bed);interiorGroup.add(bed);addCollider(3.25,-2.15,1.7,1,'inside');addInteract(bed,'REST & SAVE',2.8,()=>{state.minutes=(state.minutes+120)%1440;state.warmth=100;state.health=Math.min(100,state.health+18);saveGame();showMessage('RESTED TWO HOURS · PROGRESS SAVED')},'inside');
  const table=new THREE.Group();table.position.set(-.45,0,.2);box(2.8,.2,1.5,0x684a31,0,1,0,table);for(let sx of[-1.15,1.15])for(let sz of[-.55,.55])box(.14,1,.14,0x513822,sx,.5,sz,table);interiorGroup.add(table);addCollider(-.45,.2,1.55,.9,'inside');
  const radio=box(1.25,.7,.5,0x252a25,2.7,1.08,1.45,interiorGroup,.35,.55);box(.08,.65,.08,0x7b817a,3.1,1.68,1.45,interiorGroup,.3,.7);const dial=mesh(new THREE.SphereGeometry(.09,8,6),material(0xd0ae62,.3,.5),2.95,1.1,1.18,interiorGroup);addInteract(radio,'USE CABIN RADIO',2.6,()=>{if(state.quest===4)completeChapter();else showMessage(state.flags.tower?'A voice is trying to break through.':'Only static. The tower repeater is dead.')},'inside');
  const cabinet=box(1.8,2.5,.75,0x3e2c20,-3.75,1.25,2.85,interiorGroup);addCollider(-3.75,2.85,1,.5,'inside');addInteract(cabinet,'SEARCH CABINET',2.5,()=>{if(state.flags.cabinLooted)return showMessage('Nothing useful remains.');state.flags.cabinLooted=true;addItem('food',2);addItem('bandage',1);addItem('matches',1);showMessage('FOUND: STEW, BANDAGE, MATCHES')},'inside');
  const hearth=new THREE.Group();hearth.position.set(-3.65,0,-2.55);box(2.2,2.1,.8,0x383832,0,1.05,0,hearth);const opening=box(1.35,1.05,.08,0x090807,0,.72,.43,hearth);const flame=mesh(new THREE.ConeGeometry(.38,1.05,7),material(0xff6b24,.2,0,0xff3b12,4),0,.65,.5,hearth);flame.visible=false;const glow=new THREE.PointLight(0xff8a3c,0,28,1.4);glow.position.set(0,1,.8);hearth.add(glow);interiorGroup.add(hearth);addCollider(-3.65,-2.55,1.25,.75,'inside');const cf={g:hearth,glow,flames:[flame],lit:false,inside:true};campfires.push(cf);addInteract(opening,'LIGHT FIREPLACE',2.8,()=>lightFire(cf),'inside');
  const lamp1=new THREE.PointLight(0xffd59a,0,22,1.5);lamp1.position.set(0,3.1,0);interiorGroup.add(lamp1);const lamp2=new THREE.PointLight(0xffbd76,0,14,1.5);lamp2.position.set(3.4,2.4,1.5);interiorGroup.add(lamp2);interiorLights.push(lamp1,lamp2);
  const rug=mesh(new THREE.PlaneGeometry(3.7,2.2),material(0x5b2f2a,.95),.2,.012,-1.1,interiorGroup);rug.rotation.x=-Math.PI/2;
}
function buildWorld(){buildSky();buildTerrain();buildForest();buildCabin();buildTruck();buildDock();buildCamp();buildTower();buildMine();buildLookout();buildSalvageSites();buildInterior();buildMineInterior();buildRuinInterior();spawnAnimals();spawnPickups();buildHeldItems()}

function spawnAnimals(){for(let i=0;i<7;i++){const x=(Math.random()-.5)*260,z=(Math.random()-.5)*260;if(heightAt(x,z)<1){i--;continue}animals.push(makeDeer(x,z))}for(let i=0;i<4;i++)animals.push(makeRabbit((Math.random()-.5)*180,(Math.random()-.5)*180))}
function makeDeer(x,z){const g=new THREE.Group();g.position.set(x,heightAt(x,z),z);const body=mesh(new THREE.CapsuleGeometry(.55,1.3,4,8),material(0x76543b,.95),0,1.4,0,g);body.rotation.z=Math.PI/2;mesh(new THREE.CapsuleGeometry(.25,.5,3,6),material(0x6a4934),.85,2,0,g);for(let sx of[-.55,.55])for(let sz of[-.28,.28])box(.1,1.3,.1,0x4f3929,sx,.68,sz,g);worldGroup.add(g);return{type:'deer',g,hp:2,dir:Math.random()*6.28,speed:.7+Math.random()*.4,timer:2+Math.random()*5,dead:false}}
function makeRabbit(x,z){const g=new THREE.Group();g.position.set(x,heightAt(x,z),z);mesh(new THREE.SphereGeometry(.3,7,5),material(0x777069),0,.3,0,g);mesh(new THREE.SphereGeometry(.22,7,5),material(0x777069),.32,.45,0,g);for(let s of[-1,1]){const ear=mesh(new THREE.CapsuleGeometry(.05,.28,3,5),material(0x827971),.38,.75,s*.09,g);ear.rotation.z=-.15}worldGroup.add(g);return{type:'rabbit',g,hp:1,dir:Math.random()*6.28,speed:1.4,timer:2+Math.random()*4,dead:false}}
function spawnStalker(){if(state.flags.cleansed||enemies.some(e=>e.kind==='stalker'))return;const g=new THREE.Group();const m=material(0x0a0c0a,.9);mesh(new THREE.CapsuleGeometry(.28,3.4,5,7),m,0,2.6,0,g);const head=mesh(new THREE.SphereGeometry(.35,7,5),m,0,4.8,0,g);head.scale.y=1.5;for(let s of[-1,1])mesh(new THREE.SphereGeometry(.035,5,4),new THREE.MeshBasicMaterial({color:0xff392a}),s*.12,4.9,-.31,g);for(let s of[-1,1]){const arm=mesh(new THREE.CapsuleGeometry(.08,2.6,4,5),m,s*.52,2.7,0,g);arm.rotation.z=s*.17}const x=camera.position.x+Math.sin(state.player.yaw)*36,z=camera.position.z+Math.cos(state.player.yaw)*36;g.position.set(x,heightAt(x,z),z);worldGroup.add(g);enemies.push({g,hp:5,maxHp:5,speed:2.8,attack:0,zone:'outside',kind:'stalker',stunnedUntil:0});showMessage('A BRANCH SNAPS BEHIND YOU');threatLevel=1}
function spawnMineEnemies(){if(state.flags.cleansed||enemies.some(e=>e.zone==='mine'))return;for(const [x,z] of [[-3,-8],[3,-21],[-2,-31]]){const g=new THREE.Group(),m=material(0x111513,.8,0,0x230503,.5);mesh(new THREE.CapsuleGeometry(.23,2.4,4,6),m,0,1.8,0,g);mesh(new THREE.SphereGeometry(.29,6,5),m,0,3.35,0,g);for(const s of[-1,1])mesh(new THREE.SphereGeometry(.035,5,4),new THREE.MeshBasicMaterial({color:0xff4b2f}),s*.1,3.42,-.25,g);g.position.set(x,0,z);mineGroup.add(g);enemies.push({g,hp:3,maxHp:3,speed:2.15,attack:0,zone:'mine',kind:'shade',stunnedUntil:0})}}
function spawnPickups(){const scrap=box(.5,.3,.45,0x63706a,108,heightAt(108,78)+.4,73);addInteract(scrap,'TAKE ELECTRICAL SCRAP',2.5,()=>{if(scrap.userData.taken)return;scrap.userData.taken=true;scrap.visible=false;addItem('scrap',2);showMessage('FOUND: ELECTRICAL SCRAP')})}

const held=new THREE.Group();camera.add(held);scene.add(camera);let handModels={};function buildHeldItems(){const hand=box(.3,.3,.6,0xb58a68,.45,-.42,-.8,held);hand.rotation.x=-.3;handModels[1]=hand;const light=mesh(new THREE.CylinderGeometry(.09,.12,.55,10),material(0x343a34,.3,.7),.42,-.32,-.7,held);light.rotation.x=Math.PI/2;handModels[2]=light;const rifle=new THREE.Group();box(.12,.14,1.5,0x583a25,.35,-.35,-1.05,rifle);box(.09,.1,1.2,0x262925,.35,-.3,-2.2,rifle,.35,.7);rifle.rotation.y=-.05;held.add(rifle);handModels[3]=rifle;const axe=new THREE.Group();const handle=mesh(new THREE.CylinderGeometry(.035,.05,1.15,7),material(0x60422b),.38,-.32,-1.05,axe);handle.rotation.x=Math.PI/2;const blade=box(.45,.32,.08,0x8a918d,.38,-.28,-1.62,axe,.25,.8);held.add(axe);handModels[4]=axe;selectSlot(1)}
function selectSlot(n){state.slot=n;Object.entries(handModels).forEach(([k,v])=>v.visible=+k===n);$$('.slot').forEach((b,i)=>b.classList.toggle('active',i===n-1));if(n===2&&!state.flashlight)toggleFlashlight(true)}

function lootTruck(){if(state.flags.truckLooted)return showMessage('Empty. The battery is dead.');state.flags.truckLooted=true;addItem('fuel',1);addItem('ammo',6);showMessage('FOUND: GAS CAN + 6 ROUNDS');if(state.quest===0)setQuest(1);saveGame()}
function checkTruckParts(){if(state.quest<5)return;const ready=['battery','belt','plugs','fuel'].every(id=>hasItem(id));if(ready&&!state.flags.truckReady)setQuest(7);else if(state.quest===5)setQuest(6)}
function handleTruck(){if(state.quest<5&&!state.flags.chapter1)return lootTruck();if(state.flags.truckReady)return startTruckEscape();const needed=[['battery','BATTERY'],['belt','FAN BELT'],['plugs','SPARK PLUGS'],['fuel','FUEL']].filter(([id])=>!hasItem(id)).map(x=>x[1]);if(needed.length){if(state.quest===5)setQuest(6);discover('service');discover('shack');discover('boathouse');return showMessage(`MISSING: ${needed.join(' · ')}`,4200)}for(const id of['battery','belt','plugs','fuel'])removeItem(id,1);state.flags.truckReady=true;setQuest(7);saveGame();showMessage('TRUCK REPAIRED · INTERACT AGAIN TO LEAVE',4200)}
function useGenerator(){if(state.flags.generator)return showMessage('The generator is running. The cabin has power.');if(!hasItem('fuel'))return showMessage('The tank is dry. Find gasoline.');removeItem('fuel',1);state.flags.generator=true;discover('camp');setQuest(2);updateInteriorLights();showMessage('GENERATOR ONLINE · OLD CAMPGROUND MARKED ON MAP');ping(78,.8);saveGame()}
function repairTower(){if(state.flags.tower)return showMessage('…kzzzt… Kelley cabin, do you copy?');if(state.quest<2)return showMessage('The radio is dead. Nothing you need here yet.');if(!hasItem('fuse'))return showMessage('The repeater fuse is blown. Find a replacement.');removeItem('fuse',1);state.flags.tower=true;setQuest(3);showMessage('RADIO ONLINE · INCOMING TRANSMISSION');openNote('18:57 HOURS','RANGER COLE — FINAL TRANSMISSION',`Kelley cabin, if you can hear this, do not use the main trail.\n\nIt learned the sound of the generator. It follows electricity. It follows voices.\n\nI am leaving the tower now.\n\nThat is not me outside the door.`);spawnStalker();saveGame()}
function updateInteriorLights(){for(const l of interiorLights)l.intensity=state.flags.generator?3.8:0}
function enterCabin(){
  if(state.interior)return;state.exterior={x:camera.position.x,z:camera.position.z};state.interior=true;state.interiorMode='cabin';worldGroup.visible=false;dynamicGroup.visible=false;interiorGroup.visible=true;mineGroup.visible=false;if(stars)stars.visible=false;if(rain)rain.visible=false;if(sun)sun.visible=false;if(moon)moon.visible=false;if(hemi)hemi.visible=false;if(ambient)ambient.visible=false;scene.background.set(0x0a0b08);scene.fog=new THREE.FogExp2(0x0a0b08,.035);camera.position.set(0,1.72,2.35);state.player.yaw=Math.PI;state.player.pitch=0;velocity.set(0,0,0);state.location='KELLEY CABIN · INTERIOR';state.warmth=Math.min(100,state.warmth+16);updateInteriorLights();if(state.quest===3){setQuest(4);showMessage('DOOR LOCKED · USE THE RADIO');saveGame()}else showMessage(state.flags.generator?'THE CABIN LIGHTS HUM TO LIFE':'INSIDE KELLEY CABIN')
}
function exitCabin(){
  if(state.interiorMode!=='cabin')return;state.interior=false;state.interiorMode=null;interiorGroup.visible=false;worldGroup.visible=true;dynamicGroup.visible=true;if(stars)stars.visible=true;if(rain)rain.visible=true;if(sun)sun.visible=true;if(moon)moon.visible=true;if(hemi)hemi.visible=true;if(ambient)ambient.visible=true;camera.position.set(state.exterior.x||0,heightAt(state.exterior.x||0,state.exterior.z||7)+1.72,state.exterior.z||7);state.player.yaw=0;state.player.pitch=0;velocity.set(0,0,0);scene.fog=new THREE.FogExp2(0x425149,.008);showMessage('BACK OUTSIDE')
}
function enterMine(){if(state.interior)return;state.exterior={x:camera.position.x,z:camera.position.z};state.interior=true;state.interiorMode='mine';worldGroup.visible=false;dynamicGroup.visible=false;interiorGroup.visible=false;mineGroup.visible=true;if(stars)stars.visible=false;if(rain)rain.visible=false;if(sun)sun.visible=false;if(moon)moon.visible=false;if(hemi)hemi.visible=false;if(ambient)ambient.visible=false;scene.background.set(0x030403);scene.fog=new THREE.FogExp2(0x030403,.055);camera.position.set(0,1.72,5.3);state.player.yaw=0;state.player.pitch=0;velocity.set(0,0,0);state.location='ABANDONED MINE · LOWER WORKS';if(!state.flags.cleansed){setQuest(8);spawnMineEnemies();showMessage('THE ROCK IS BREATHING',3200)}else showMessage('ONLY WATER MOVES IN THE DARK')}
function exitMine(){if(state.interiorMode!=='mine')return;state.interior=false;state.interiorMode=null;mineGroup.visible=false;worldGroup.visible=true;dynamicGroup.visible=true;if(stars)stars.visible=true;if(rain)rain.visible=true;if(sun)sun.visible=true;if(moon)moon.visible=true;if(hemi)hemi.visible=true;if(ambient)ambient.visible=true;camera.position.set(108,heightAt(108,72)+1.72,72);state.player.yaw=Math.PI;state.player.pitch=0;velocity.set(0,0,0);scene.fog=new THREE.FogExp2(0x425149,.008);showMessage(state.flags.cleansed?'THE FOREST IS SILENT':'THE MINE LETS YOU LEAVE')}
function enterRuin(id){if(state.interior||!POIS[id])return;state.exterior={x:camera.position.x,z:camera.position.z};state.interior=true;state.interiorMode='ruin';state.currentRuin=id;worldGroup.visible=false;dynamicGroup.visible=false;interiorGroup.visible=false;mineGroup.visible=false;ruinGroup.visible=true;if(stars)stars.visible=false;if(rain)rain.visible=false;if(sun)sun.visible=false;if(moon)moon.visible=false;if(hemi)hemi.visible=false;if(ambient)ambient.visible=false;scene.background.set(0x080a08);scene.fog=new THREE.FogExp2(0x080a08,.04);camera.position.set(0,1.72,3.25);state.player.yaw=0;state.player.pitch=0;velocity.set(0,0,0);state.location=`${POIS[id].label.toUpperCase()} · INTERIOR`;discover(id);showMessage('THREE PLACES INSIDE MAY STILL HOLD SUPPLIES')}
function exitRuin(){if(state.interiorMode!=='ruin')return;state.interior=false;state.interiorMode=null;state.currentRuin=null;ruinGroup.visible=false;worldGroup.visible=true;dynamicGroup.visible=true;if(stars)stars.visible=true;if(rain)rain.visible=true;if(sun)sun.visible=true;if(moon)moon.visible=true;if(hemi)hemi.visible=true;if(ambient)ambient.visible=true;const x=state.exterior.x||0,z=state.exterior.z||7;camera.position.set(x,heightAt(x,z)+1.72,z);state.player.yaw=0;state.player.pitch=0;velocity.set(0,0,0);scene.fog=new THREE.FogExp2(0x425149,.008);saveGame();showMessage('BACK OUTSIDE')}
function searchRuin(spot){const id=state.currentRuin,key=`${id}:${spot}`;if(!id||!RUIN_LOOT[id])return;state.flags.ruinLoot=state.flags.ruinLoot||{};if(state.flags.ruinLoot[key])return showMessage('You already searched here.');state.flags.ruinLoot[key]=true;grantLoot(RUIN_LOOT[id][spot]);saveGame()}
function completeChapter(){if(state.flags.chapter1)return;state.flags.chapter1=true;state.flags.ending=true;for(const id of['mine','garage','trapper','shelter'])if(!state.discovered.includes(id))state.discovered.push(id);setQuest(5);state.ending=true;state.paused=true;document.exitPointerLock?.();saveGame();const elapsed=Math.max(1,Math.floor((performance.now()-state.startTime)/60000));$('#endingStats').innerHTML=`<span>${elapsed} MINUTES</span><span>${state.fishCaught} FISH</span><span>${state.deerHunted} DEER</span><span>${state.shots} SHOTS</span>`;$('#ending').classList.remove('hidden')}
function destroyHeart(){if(state.flags.cleansed)return showMessage('The stone is cold. Nothing remains.');if(!hasItem('fuel')||!hasItem('matches'))return showMessage('YOU NEED GASOLINE AND MATCHES',3600);removeItem('fuel',1);removeItem('matches',1);state.flags.cleansed=true;for(const e of enemies){e.g.visible=false}enemies.length=0;threatLevel=0;setQuest(9);saveGame();showFinalEnding('THE ROOT BELOW','BURNED OUT','The buried heart collapses into ash. Every moving shape in Cedar Lake goes still. The woods are yours now.','RETURN TO THE QUIET WOODS');ping(38,2.2,.65)}
function showFinalEnding(kicker,title,copy,button){state.ending=true;state.paused=true;document.exitPointerLock?.();$('#finalKicker').textContent=kicker;$('#finalTitle').textContent=title;$('#finalCopy').textContent=copy;$('#finalContinue').textContent=button;$('#finalEnding').classList.remove('hidden')}
function startTruckEscape(){if(state.cutscene)return;state.cutscene=true;state.paused=true;state.ending=true;truckCutsceneTime=0;document.exitPointerLock?.();$('#hud').classList.add('hidden');$('#truckCutscene').classList.remove('hidden');$('#cutsceneCaption').textContent='THE ENGINE TURNS OVER.';showMessage('');ping(62,1.2,.5)}
function updateTruckCutscene(dt){if(!state.cutscene||!truckGroup)return;truckCutsceneTime+=dt;const t=truckCutsceneTime,speed=10;truckGroup.position.z+=dt*speed;const roadIndex=(20-truckGroup.position.z)/1.55;truckGroup.position.x=-3-Math.sin(roadIndex*.13)*10;truckGroup.position.y=heightAt(truckGroup.position.x,truckGroup.position.z);truckGroup.rotation.y=Math.PI/2;const desired=new THREE.Vector3(truckGroup.position.x-10,truckGroup.position.y+6,truckGroup.position.z-13);camera.position.lerp(desired,Math.min(1,dt*2.5));camera.lookAt(truckGroup.position.x,truckGroup.position.y+1.5,truckGroup.position.z+4);if(t>2.7)$('#cutsceneCaption').textContent='THE TREELINE RUNS BESIDE YOU.';if(t>5.3)$('#cutsceneCaption').textContent='SOMETHING KEEPS PACE—THEN FALLS BEHIND.';if(t>8){state.cutscene=false;$('#truckCutscene').classList.add('hidden');showFinalEnding('ESCAPE ENDING','COUNTY ROAD 6','The truck reaches the county road before dawn. Cedar Lake disappears in the mirror—but whatever lives there is still alive.','RETURN TO TITLE')}}
function lightFire(cf){if(cf.lit)return showMessage('The fire is already burning.');if(!hasItem('wood')||!hasItem('matches'))return showMessage('You need firewood and matches.');removeItem('wood',1);cf.lit=true;cf.glow.intensity=5.8;(cf.flames||[]).forEach(f=>f.visible=true);state.flags.campfire=true;showMessage('FIRE LIT · WARMTH RESTORED');ping(220,.35)}

function setQuest(q){state.quest=q;if(q>=5)for(const id of['mine','garage','trapper','shelter'])if(!state.discovered.includes(id))state.discovered.push(id);const d=questData[q]||questData[0];$('#questChapter').textContent=q>=5?'CHAPTER II · THE ROOT BELOW':'CHAPTER I · THE SILENT RANGER';$('#questTitle').textContent=d[0];$('#questText').textContent=d[1];showMessage(`NEW OBJECTIVE · ${d[0]}`)}
function discover(id){if(state.discovered.includes(id))return;state.discovered.push(id);showMessage(`LOCATION DISCOVERED · ${POIS[id]?.label||id.toUpperCase()}`)}
function addItem(id,n=1){if(id==='ammo'){state.reserve=(state.reserve||0)+n;state.inventory.ammo=state.reserve}else state.inventory[id]=(state.inventory[id]||0)+n;renderInventory()}function removeItem(id,n=1){if(id==='ammo'){state.reserve=Math.max(0,(state.reserve||0)-n);state.inventory.ammo=state.reserve}else{state.inventory[id]=Math.max(0,(state.inventory[id]||0)-n);if(!state.inventory[id])delete state.inventory[id]}renderInventory()}function hasItem(id,n=1){return(id==='ammo'?state.reserve:(state.inventory[id]||0))>=n}
function renderInventory(){const grid=$('#inventoryGrid');grid.innerHTML='';Object.entries(state.inventory).forEach(([id,n])=>{const d=itemDefs[id]||[id,'','?'],b=document.createElement('button');b.className='inv-item'+(selectedInv===id?' selected':'');b.innerHTML=`<span class="inv-icon">${d[2]}</span><strong>${d[0]}</strong><b>${n}</b>`;b.onclick=()=>{selectedInv=id;$('#itemName').textContent=d[0];$('#itemDesc').textContent=d[1];renderInventory()};grid.appendChild(b)});$('#ammoText').textContent=`${state.ammo} / ${state.reserve}`;renderRecipes()}
function renderRecipes(){const recipes=[['bandage','FIELD DRESSING',{wood:1,scrap:1}],['ammo','IMPROVISED ROUNDS',{scrap:1,wood:1}],['food','COOKED MEAL',{fish:1,wood:1}]],wrap=$('#recipes');wrap.innerHTML='';for(const [out,name,req] of recipes){const ok=Object.entries(req).every(([i,n])=>hasItem(i,n)),el=document.createElement('div');el.className='recipe';el.innerHTML=`<strong>${name}</strong><p>${Object.entries(req).map(([i,n])=>`${n} ${itemDefs[i][0]}`).join(' + ')}</p><button ${ok?'':'disabled'}>CRAFT</button>`;el.querySelector('button').onclick=()=>{Object.entries(req).forEach(([i,n])=>removeItem(i,n));addItem(out,1);showMessage(`CRAFTED: ${name}`)};wrap.appendChild(el)}}
function useSelectedItem(){if(selectedInv==='bandage'&&hasItem('bandage')){removeItem('bandage');state.health=Math.min(100,state.health+30);showMessage('HEALTH RESTORED')}else if(selectedInv==='food'&&hasItem('food')){removeItem('food');state.hunger=Math.min(100,state.hunger+38);showMessage('HUNGER RESTORED')}else if(selectedInv==='fish'&&hasItem('fish')){removeItem('fish');state.hunger=Math.min(100,state.hunger+22);showMessage('RAW FISH · NOT YOUR BEST DECISION')}else showMessage('That item cannot be used here.')}

function openInventory(){if(!state.running)return;state.paused=true;document.exitPointerLock?.();renderInventory();$('#inventory').classList.remove('hidden')}function openMap(){if(!state.running)return;state.paused=true;document.exitPointerLock?.();drawMap();$('#mapPanel').classList.remove('hidden')}function closePanels(){for(const id of['inventory','mapPanel'])$('#'+id).classList.add('hidden');if(state.running&&!state.dead&&!state.ending){state.paused=false;lockPointer()}}
function openNote(date,title,body){state.paused=true;document.exitPointerLock?.();$('#noteDate').textContent=date;$('#noteTitle').textContent=title;$('#noteBody').textContent=body;$('#notePanel').classList.remove('hidden')}
function closeNote(){ $('#notePanel').classList.add('hidden');if(state.running){state.paused=false;lockPointer()}}
function drawMap(){const c=$('#mapCanvas'),x=c.getContext('2d'),W=c.width,H=c.height;x.fillStyle='#c8b98f';x.fillRect(0,0,W,H);x.globalAlpha=.18;x.strokeStyle='#263728';for(let i=0;i<35;i++){x.beginPath();for(let px=0;px<W;px+=10){const py=H*.5+Math.sin(px*.018+i)*20+(i-17)*15;if(px===0)x.moveTo(px,py);else x.lineTo(px,py)}x.stroke()}x.globalAlpha=1;x.fillStyle='#567c78';x.beginPath();x.ellipse(mapX(55),mapZ(-58),118,83,-.3,0,7);x.fill();x.fillStyle='#314b34';for(let i=0;i<100;i++){const px=Math.random()*W,py=Math.random()*H;x.beginPath();x.moveTo(px,py);x.lineTo(px-5,py+12);x.lineTo(px+5,py+12);x.fill()}for(const [id,p]of Object.entries(POIS)){if(!state.discovered.includes(id)&&id!=='cabin')continue;x.fillStyle='#27291f';x.beginPath();x.arc(mapX(p.x),mapZ(p.z),5,0,7);x.fill();x.font='12px DM Mono';x.fillText(p.label.toUpperCase(),mapX(p.x)+9,mapZ(p.z)+4)}x.fillStyle='#ef8d47';x.beginPath();x.arc(mapX(camera.position.x),mapZ(camera.position.z),7,0,7);x.fill();x.strokeStyle='#ef8d47';x.beginPath();x.moveTo(mapX(camera.position.x),mapZ(camera.position.z));x.lineTo(mapX(camera.position.x)+Math.sin(state.player.yaw)*20,mapZ(camera.position.z)+Math.cos(state.player.yaw)*20);x.stroke();function mapX(v){return(v+210)/420*W}function mapZ(v){return(v+210)/420*H}}

function startFishing(){state.paused=true;document.exitPointerLock?.();fishPhase='waiting';$('#fishing').classList.remove('hidden');$('#fishTitle').textContent='Line is in the water…';$('#fishText').textContent='Wait for the strike.';$('#reelBtn').disabled=true;fishTimer=setTimeout(()=>{fishPhase='strike';$('#fishTitle').textContent='STRIKE!';$('#fishText').textContent='Reel while the needle crosses the green zone.';$('#reelBtn').disabled=false},1800+Math.random()*3500)}
function stopFishing(){clearTimeout(fishTimer);$('#fishing').classList.add('hidden');state.paused=false;lockPointer();fishPhase='idle'}function reelFish(){if(fishPhase!=='strike')return;const needle=parseFloat($('#fishNeedle').style.left)||0,zone=parseFloat($('#fishZone').style.left)||44;if(needle>zone&&needle<zone+18){addItem('fish',1);state.fishCaught++;$('#fishTitle').textContent='WALLEYE — 19 INCHES';$('#fishText').textContent='A good fish. The lake goes perfectly still.';ping(520,.4)}else{$('#fishTitle').textContent='IT GOT AWAY';$('#fishText').textContent='The line snaps back empty.'}fishPhase='done';$('#reelBtn').disabled=true;setTimeout(stopFishing,1600)}

function shoot(){if(state.slot!==3||state.paused||reloadTimer)return;if(state.ammo<=0){showMessage('EMPTY · PRESS R TO RELOAD');ping(80,.12);return}state.ammo--;state.shots++;renderInventory();ping(95,.18);held.position.z=.15;setTimeout(()=>held.position.z=0,80);raycaster.setFromCamera({x:0,y:0},camera);const zone=state.interiorMode==='mine'?'mine':'outside',targets=[...(!state.interior?animals.filter(a=>!a.dead):[]),...enemies.filter(e=>e.zone===zone&&e.g.visible)].map(a=>a.g);const hits=raycaster.intersectObjects(targets,true);if(hits.length){let root=hits[0].object;while(root.parent&&!targets.includes(root))root=root.parent;const animal=animals.find(a=>a.g===root),enemy=enemies.find(a=>a.g===root);if(animal){animal.hp--;if(animal.hp<=0)killAnimal(animal)}if(enemy){enemy.hp--;showMessage(enemy.hp>0?'IT STAGGERS — KEEP FIRING':enemy.kind==='stalker'?'IT FOLDS INTO THE BRUSH — 45 SECONDS':'THE SHADE BREAKS APART');if(enemy.hp<=0){enemy.g.visible=false;if(enemy.kind==='stalker'){enemy.stunnedUntil=performance.now()+45000;threatLevel=0}else enemies.splice(enemies.indexOf(enemy),1)}}}else if(!state.interior){animals.forEach(a=>{if(!a.dead&&a.g.position.distanceTo(camera.position)<75)a.timer=0})}}
function swingAxe(){if(state.slot!==4||state.paused)return;held.rotation.x=-.6;setTimeout(()=>held.rotation.x=0,190);const near=trees.find(t=>dist2(camera.position.x,camera.position.z,t.x,t.z)<3);if(near){addItem('wood',1);state.woodCut++;showMessage('COLLECTED: DRY FIREWOOD');ping(130,.18)}else ping(160,.1)}
function reload(){if(reloadTimer||state.slot!==3||state.ammo===6||state.reserve<=0)return;showMessage('RELOADING…');reloadTimer=setTimeout(()=>{const n=Math.min(6-state.ammo,state.reserve);state.ammo+=n;state.reserve-=n;state.inventory.ammo=state.reserve;reloadTimer=0;renderInventory();ping(260,.12)},1100)}
function killAnimal(a){a.dead=true;a.g.rotation.z=Math.PI/2;a.g.position.y=heightAt(a.g.position.x,a.g.position.z)+.4;if(a.type==='deer'){state.deerHunted++;addItem('venison',2);showMessage('DEER HARVESTED · 2 VENISON')}else showMessage('The rabbit disappears into the brush.')}

function initAudio(){if(audio)return;audio=new(window.AudioContext||window.webkitAudioContext)();master=audio.createGain();master.gain.value=.12;master.connect(audio.destination);windOsc=audio.createOscillator();const filter=audio.createBiquadFilter();droneGain=audio.createGain();windOsc.type='sawtooth';windOsc.frequency.value=42;filter.type='lowpass';filter.frequency.value=100;droneGain.gain.value=.12;windOsc.connect(filter).connect(droneGain).connect(master);windOsc.start()}
function ping(freq=300,d=.25,vol=.22){if(!audio)return;const o=audio.createOscillator(),g=audio.createGain();o.frequency.setValueAtTime(freq,audio.currentTime);o.frequency.exponentialRampToValueAtTime(Math.max(30,freq*.6),audio.currentTime+d);g.gain.setValueAtTime(vol,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+d);o.connect(g).connect(master);o.start();o.stop(audio.currentTime+d)}
function footstep(){if(!audio)return;const o=audio.createOscillator(),g=audio.createGain();o.type='triangle';o.frequency.value=65+Math.random()*25;g.gain.setValueAtTime(.08,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+.07);o.connect(g).connect(master);o.start();o.stop(audio.currentTime+.08)}

function showMessage(text,d=2200){$('#message').textContent=text;$('#message').classList.add('show');clearTimeout(messageTimer);messageTimer=setTimeout(()=>$('#message').classList.remove('show'),d)}
function updateHUD(){const set=(id,v)=>$('#'+id).style.width=clamp(v,0,100)+'%';set('healthBar',state.health);set('staminaBar',state.stamina);set('warmthBar',state.warmth);set('hungerBar',state.hunger);$('#healthText').textContent=Math.ceil(state.health);const hrs=Math.floor(state.minutes/60)%24,mins=Math.floor(state.minutes%60),amp=hrs>=12?'PM':'AM';$('#timeText').textContent=`${hrs%12||12}:${String(mins).padStart(2,'0')} ${amp}`;$('#dayText').textContent=`DAY ${state.day} · ${state.weather}`;$('#location').textContent=state.location.toUpperCase();$('#ammoText').textContent=`${state.ammo} / ${state.reserve}`}
function updateLocation(){if(state.interior){state.location=state.interiorMode==='mine'?'ABANDONED MINE · LOWER WORKS':state.interiorMode==='ruin'?`${POIS[state.currentRuin]?.label||'ABANDONED BUILDING'} · INTERIOR`:'KELLEY CABIN · INTERIOR';return}let best=['NORTH WOODS',999];for(const [id,p]of Object.entries(POIS)){const d=dist2(camera.position.x,camera.position.z,p.x,p.z);if(d<best[1]&&d<(id==='lake'?60:22))best=[p.label,d,id]}state.location=best[0];if(best[2])discover(best[2])}
function updateDayNight(dt){state.minutes+=dt*2.2;if(state.minutes>=1440){state.minutes-=1440;state.day++}state.hunger=clamp(state.hunger-dt*.025,0,100);if(state.interior){if(state.interiorMode==='cabin')state.warmth=clamp(state.warmth+dt*(state.flags.generator?.6:.28),0,100);else state.warmth=clamp(state.warmth-dt*.06,0,100);const insideColor=state.interiorMode==='mine'?0x030403:state.interiorMode==='ruin'?0x080a08:0x0a0b08;scene.background.set(insideColor);if(scene.fog){scene.fog.color.set(insideColor);scene.fog.density=state.interiorMode==='mine'?.055:state.interiorMode==='ruin'?.04:.035}if(state.hunger<5)damage(dt*.45,'Hunger took you.');return}const h=state.minutes/60,angle=(h-6)/24*Math.PI*2,sunY=Math.sin(angle),sunX=Math.cos(angle);sun.position.set(sunX*150,sunY*170,-80);moon.position.set(-sunX*130,-sunY*140,60);const daylight=clamp((sunY+.12)*1.2,0,1),night=1-daylight;sun.intensity=daylight*2.8;moon.intensity=night*.7;hemi.intensity=.22+daylight*1.2;ambient.intensity=.12+daylight*.38;stars.material.opacity=clamp(night*1.3-.2,0,.9);const dayColor=new THREE.Color(0x53675d),duskColor=new THREE.Color(0x5b3c35),nightColor=new THREE.Color(0x050b12);let sky;if(daylight>.25)sky=duskColor.clone().lerp(dayColor,clamp((daylight-.25)/.55,0,1));else sky=nightColor.clone().lerp(duskColor,daylight/.25);if(state.weather==='FOG'||state.weather==='RAIN')sky.multiplyScalar(.65);scene.background.copy(sky);scene.fog.color.copy(sky);scene.fog.density=state.weather==='FOG'?.018:state.weather==='RAIN'?.012:.0075;rain.material.opacity=state.weather==='RAIN'?.6:0;const cold=night*(state.weather==='RAIN'?1.3:1);state.warmth=clamp(state.warmth-dt*(.08+.18*cold),0,100);for(const cf of campfires)if(cf.lit&&!cf.inside&&camera.position.distanceTo(cf.g.position)<12)state.warmth=clamp(state.warmth+dt*3.2,0,100);if(state.warmth<10||state.hunger<5)damage(dt*(state.warmth<10?.9:.45),'Exposure took you.');if(night>.74&&state.quest>=2&&!state.flags.cleansed&&!enemies.some(e=>e.kind==='stalker')&&Math.random()<dt*.003)spawnStalker()}
function updateWeather(dt){if(state.interior)return;state.weatherTimer-=dt;if(state.weatherTimer<=0){const r=Math.random();state.weather=r<.25?'RAIN':r<.47?'FOG':'CLEAR';state.weatherTimer=90+Math.random()*160;if(state.weather==='RAIN'&&Math.random()<.6)setTimeout(lightning,3000+Math.random()*6000)}if(state.weather==='RAIN'){const p=rain.geometry.attributes.position;for(let i=0;i<p.count;i++){let y=p.getY(i)-dt*38;if(y<0)y=65;p.setY(i,y)}p.needsUpdate=true;rain.position.x=camera.position.x;rain.position.z=camera.position.z}}
function lightning(){if(state.weather!=='RAIN'||state.interior)return;$('#lightning').classList.remove('flash');void $('#lightning').offsetWidth;$('#lightning').classList.add('flash');ping(42,.8,.4);setTimeout(()=>{if(state.weather==='RAIN'&&!state.interior)lightning()},9000+Math.random()*16000)}
function damage(n,reason='Something in the woods found you.'){if(state.dead)return;state.health=clamp(state.health-n,0,100);$('#damageFlash').classList.remove('hit');void $('#damageFlash').offsetWidth;$('#damageFlash').classList.add('hit');if(state.health<=0)die(reason)}function die(reason){state.dead=true;state.paused=true;document.exitPointerLock?.();$('#deathReason').textContent=reason;$('#death').classList.remove('hidden')}

function updatePlayer(dt){if(!state.running||state.paused)return;state.player.yaw=state.player.yaw||0;camera.rotation.y=state.player.yaw;camera.rotation.x=state.player.pitch;let x=(keys.KeyD?1:0)-(keys.KeyA?1:0),z=(keys.KeyS?1:0)-(keys.KeyW?1:0);if(mobileMove.active){x=mobileMove.x;z=-mobileMove.y}moveVec.set(x,0,z);if(moveVec.lengthSq()>1)moveVec.normalize();moveVec.applyAxisAngle(up,state.player.yaw);const sprint=keys.ShiftLeft&&state.stamina>1&&moveVec.lengthSq()>.1,speed=(sprint?8.5:4.6)*(state.interior?0.72:(heightAt(camera.position.x,camera.position.z)<.3?.48:1));state.stamina=clamp(state.stamina+(sprint?-24:15)*dt,0,100);velocity.x+=(moveVec.x*speed-velocity.x)*Math.min(1,dt*9);velocity.z+=(moveVec.z*speed-velocity.z)*Math.min(1,dt*9);let nx=camera.position.x+velocity.x*dt,nz=camera.position.z+velocity.z*dt;if(state.interiorMode==='mine'){nx=clamp(nx,-6.65,6.65);nz=clamp(nz,-41,7)}else if(state.interiorMode==='ruin'){nx=clamp(nx,-5.12,5.12);nz=clamp(nz,-4.08,4.08)}else if(state.interior){nx=clamp(nx,-4.62,4.62);nz=clamp(nz,-3.48,3.48)}else{nx=clamp(nx,-202,202);nz=clamp(nz,-202,202)}if(!hitsCollider(nx,nz)){camera.position.x=nx;camera.position.z=nz}else{velocity.x*=.18;velocity.z*=.18}const targetY=state.interior?1.72:heightAt(camera.position.x,camera.position.z)+1.72;camera.position.y=lerp(camera.position.y,targetY,Math.min(1,dt*18));if(moveVec.lengthSq()>.1){footTimer-=dt;if(footTimer<=0){footstep();footTimer=sprint?.32:.52}camera.position.y+=Math.sin(performance.now()*.013)*(sprint?.045:.026);held.rotation.z=Math.sin(performance.now()*.009)*.012}else footTimer=0;if(!state.interior){state.player.x=camera.position.x;state.player.z=camera.position.z}updateInteraction();updateCompass();updateLocation()}
function updateCompass(){let deg=(state.player.yaw*180/Math.PI)%360;if(deg<0)deg+=360;const names=['N','NE','E','SE','S','SW','W','NW'];$('#compassText').textContent=names[Math.round(deg/45)%8];$('#compassTick').style.left=(50+(deg%45-22.5)/45*45)+'%'}
function updateInteraction(){activeInteract=null;let dmin=999;const zone=state.interiorMode==='mine'?'mine':state.interiorMode==='ruin'?'ruin':state.interior?'inside':'outside';for(const it of interactables){if(it.zone!==zone||!it.obj.visible)continue;it.obj.getWorldPosition(tmp);const d=camera.position.distanceTo(tmp);if(d<it.range&&d<dmin){dmin=d;activeInteract=it}}$('#interactPrompt').classList.toggle('show',!!activeInteract);$('#reticle').classList.toggle('hot',!!activeInteract);if(activeInteract)$('#promptText').textContent=activeInteract.label}
function updateAnimals(dt){for(const a of animals){if(a.dead)continue;a.timer-=dt;const d=a.g.position.distanceTo(camera.position);if(d<18||a.timer<=0){if(d<18){const dx=a.g.position.x-camera.position.x,dz=a.g.position.z-camera.position.z;a.dir=Math.atan2(dx,dz);a.speed=a.type==='deer'?5:4}else{a.dir+= (Math.random()-.5)*2;a.speed=a.type==='deer'?1:.8;a.timer=3+Math.random()*6}}a.g.position.x+=Math.sin(a.dir)*a.speed*dt;a.g.position.z+=Math.cos(a.dir)*a.speed*dt;a.g.position.y=heightAt(a.g.position.x,a.g.position.z);a.g.rotation.y=a.dir}}
function updateEnemies(dt){let close=false;const zone=state.interiorMode==='mine'?'mine':'outside';for(const e of enemies){if(e.zone!==zone)continue;if(!e.g.visible){if(e.kind==='stalker'&&!state.flags.cleansed&&performance.now()>=e.stunnedUntil){const a=state.player.yaw+Math.PI+(Math.random()-.5)*1.3,x=camera.position.x+Math.sin(a)*34,z=camera.position.z+Math.cos(a)*34;e.g.position.set(x,heightAt(x,z),z);e.hp=e.maxHp;e.g.visible=true;showMessage('A LOW WHISTLE RETURNS FROM THE TREES',3200);threatLevel=1}continue}const dx=camera.position.x-e.g.position.x,dz=camera.position.z-e.g.position.z,d=Math.hypot(dx,dz);if(d<45){close=true;const a=Math.atan2(dx,dz);e.g.position.x+=Math.sin(a)*e.speed*dt;e.g.position.z+=Math.cos(a)*e.speed*dt;e.g.position.y=e.zone==='mine'?0:heightAt(e.g.position.x,e.g.position.z);e.g.rotation.y=a}if(d<2.2){e.attack-=dt;if(e.attack<=0){damage(e.kind==='shade'?10:14,e.zone==='mine'?'The lower works closed around you.':'It followed your light through the pines.');e.attack=1.2;ping(50,.4,.5)}}}$('#threat').classList.toggle('show',close||(zone==='outside'&&threatLevel>0));if(close&&audio)droneGain.gain.setTargetAtTime(.3,audio.currentTime,.2);else if(audio)droneGain.gain.setTargetAtTime(.12,audio.currentTime,.7)}
function animateWorld(t,dt){if(water){water.material.opacity=.8+Math.sin(t*.001)*.035;water.rotation.z=Math.sin(t*.0001)*.002}for(const p of particles){if(p.type==='beacon')p.obj.intensity=1.5+Math.sin(t*.004)*1.2;if(p.type==='heart'&&!state.flags.cleansed){p.obj.scale.set(1+Math.sin(t*.006)*.08,1.4+Math.sin(t*.006)*.12,1+Math.sin(t*.006)*.08);p.glow.intensity=6+Math.sin(t*.006)*2}}for(const cf of campfires)if(cf.lit){cf.glow.intensity=5.2+Math.random()*1.2;(cf.flames||[]).forEach((f,i)=>{f.scale.y=.82+Math.sin(t*.012+i)*.22;f.rotation.y+=dt*1.4})}if(fishPhase==='strike'){const left=(Math.sin(t*.006)+1)*41;$('#fishNeedle').style.left=left+'%';$('#fishZone').style.left=(38+Math.sin(t*.0013)*20)+'%'}}
function interact(){if(activeInteract&&!state.paused)activeInteract.action()}
function toggleFlashlight(force){state.flashlight=typeof force==='boolean'?force:!state.flashlight;flashlight.intensity=state.flashlight?10:0;if(state.flashlight)ping(420,.08,.12)}

function lockPointer(){if(matchMedia('(pointer:coarse)').matches)return;renderer.domElement.requestPointerLock?.()}document.addEventListener('pointerlockchange',()=>{state.locked=document.pointerLockElement===renderer.domElement;if(state.running&&!state.locked&&!state.paused&&!state.ending&&!state.dead)pauseGame()});document.addEventListener('mousemove',e=>{if(!state.locked||state.paused)return;state.player.yaw-=e.movementX*.0018;state.player.pitch=clamp(state.player.pitch-e.movementY*.0018,-1.45,1.45)});
addEventListener('keydown',e=>{keys[e.code]=true;if(e.repeat)return;if(e.code==='KeyE')interact();if(e.code==='KeyF')toggleFlashlight();if(e.code==='KeyR')reload();if(e.code==='Tab'){e.preventDefault();openInventory()}if(e.code==='KeyM')openMap();if(/^Digit[1-4]$/.test(e.code))selectSlot(+e.code.slice(-1));if(e.code==='Escape'&&state.running&&!state.paused)pauseGame()});addEventListener('keyup',e=>keys[e.code]=false);renderer.domElement.addEventListener('mousedown',e=>{if(!state.running)return;if(!state.locked&&!matchMedia('(pointer:coarse)').matches){lockPointer();return}if(e.button===0){if(state.slot===3)shoot();else if(state.slot===4)swingAxe()}});

function startGame(saved=null){initAudio();const flagDefaults={truckLooted:false,generator:false,tower:false,note:false,campfire:false,cabinLooted:false,ending:false,chapter1:false,serviceLooted:false,shackLooted:false,boathouseLooted:false,garageLooted:false,trapperLooted:false,shelterLooted:false,ruinLoot:{},truckReady:false,cleansed:false};Object.assign(state,saved||{});state.inventory={knife:1,flashlight:1,rifle:1,axe:1,ammo:state.reserve||18,wood:2,matches:1,food:2,bandage:1,...(saved?.inventory||state.inventory)};state.flags={...flagDefaults,...(saved?.flags||state.flags)};state.flags.ruinLoot={...(saved?.flags?.ruinLoot||state.flags.ruinLoot||{})};state.player={x:0,z:9,yaw:Math.PI,pitch:0,...(saved?.player||state.player)};state.discovered=Array.isArray(state.discovered)?state.discovered:['cabin'];if(state.quest>=2&&!state.discovered.includes('camp'))state.discovered.push('camp');if(state.quest>=5||state.flags.ending){state.quest=Math.max(5,state.quest||0);state.flags.chapter1=true;if(!state.discovered.includes('mine'))state.discovered.push('mine')}state.inventory.ammo=state.reserve||0;state.interior=false;state.interiorMode=null;state.currentRuin=null;state.cutscene=false;worldGroup.visible=true;dynamicGroup.visible=true;interiorGroup.visible=false;mineGroup.visible=false;ruinGroup.visible=false;if(stars)stars.visible=true;if(rain)rain.visible=true;if(sun)sun.visible=true;if(moon)moon.visible=true;if(hemi)hemi.visible=true;if(ambient)ambient.visible=true;state.running=true;state.paused=false;state.dead=false;state.ending=false;state.startTime=performance.now();camera.position.set(state.player.x,heightAt(state.player.x,state.player.z)+1.72,state.player.z);setQuest(state.quest);$$('.screen').forEach(s=>{if(!['loading','error'].includes(s.id))s.classList.add('hidden')});$('#menu').classList.add('hidden');$('#hud').classList.remove('hidden');renderInventory();updateHUD();selectSlot(state.slot);toggleFlashlight(state.flashlight);updateInteriorLights();if(state.quest>=3&&!state.flags.cleansed)spawnStalker();lockPointer();showMessage(saved?'SAVE RESTORED':state.quest>=5?'CHAPTER II · THE ROOT BELOW':'CHAPTER I · THE SILENT RANGER');saveGame()}
function pauseGame(){if(!state.running||state.dead||state.ending)return;state.paused=true;document.exitPointerLock?.();$('#pause').classList.remove('hidden')}function resumeGame(){$('#pause').classList.add('hidden');state.paused=false;lockPointer()}function resetGame(){localStorage.removeItem(SAVE_KEY);location.reload()}
function saveGame(){if(!state.running)return;if(!state.interior&&!state.cutscene){state.player.x=camera.position.x;state.player.z=camera.position.z}const safe=JSON.parse(JSON.stringify(state));safe.interior=false;safe.interiorMode=null;safe.currentRuin=null;safe.cutscene=false;delete safe.running;delete safe.paused;delete safe.locked;delete safe.dead;delete safe.ending;delete safe.startTime;localStorage.setItem(SAVE_KEY,JSON.stringify(safe));showSaveIndicator()}
function loadGame(){try{return JSON.parse(localStorage.getItem(SAVE_KEY))}catch{return null}}function showSaveIndicator(){const old=$('#dayText').textContent;$('#dayText').textContent='PROGRESS SAVED';setTimeout(()=>$('#dayText').textContent=old,900)}

function registerWebMCP(){const c=document.modelContext;if(!c?.registerTool)return;const reg=t=>{try{void Promise.resolve(c.registerTool(t)).catch(()=>{})}catch{}};reg({name:'read_survival_status',title:'Read survival status',description:'Read current health, supplies, location, time, and objective without changing the game.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:false},execute:()=>({location:state.location,health:Math.round(state.health),stamina:Math.round(state.stamina),warmth:Math.round(state.warmth),hunger:Math.round(state.hunger),time:$('#timeText').textContent,weather:state.weather,objective:questData[state.quest]?.[1],inventory:state.inventory})});reg({name:'open_field_map',title:'Open field map',description:'Pause the running game and open the same Cedar Lake map available with the M key.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:()=>{if(!state.running)throw new Error('Game has not started');openMap();return{opened:true,discovered:state.discovered}}});reg({name:'save_game_progress',title:'Save game progress',description:'Save the current single-player progress to this browser, identical to the visible Save Game action.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:()=>{if(!state.running)throw new Error('Game has not started');saveGame();return{saved:true,quest:state.quest,location:state.location}}})}

$('#newGame').onclick=()=>{if(localStorage.getItem(SAVE_KEY)&&!confirm('Start over and replace your current save?'))return;localStorage.removeItem(SAVE_KEY);startGame()};$('#continueGame').onclick=()=>startGame(loadGame());$('#controlsBtn').onclick=()=>$('#controls').classList.remove('hidden');$('#closeControls').onclick=()=>$('#controls').classList.add('hidden');$('#resumeBtn').onclick=resumeGame;$('#saveBtn').onclick=()=>{saveGame();resumeGame()};$('#restartBtn').onclick=resetGame;$('#deathRestart').onclick=resetGame;$('#loadSave').onclick=()=>{const s=loadGame();$('#death').classList.add('hidden');startGame(s)};$('#keepExploring').onclick=()=>{$('#ending').classList.add('hidden');state.ending=false;state.paused=false;discover('mine');checkTruckParts();saveGame();lockPointer()};$('#finalContinue').onclick=()=>{if(state.flags.cleansed){$('#finalEnding').classList.add('hidden');state.ending=false;state.paused=false;if(state.interiorMode==='mine')exitMine();lockPointer()}else location.reload()};$$('.close-panel').forEach(b=>b.onclick=closePanels);$('#closeNote').onclick=closeNote;$('#useItem').onclick=useSelectedItem;$('#leaveFishing').onclick=stopFishing;$('#reelBtn').onclick=reelFish;$$('.slot').forEach((b,i)=>b.onclick=()=>selectSlot(i+1));
const mobileMove={active:false,x:0,y:0};let joyId=null,lookId=null,lookLast={x:0,y:0},lookStart={x:0,y:0};const joy=$('#mobileStick'),knob=joy.querySelector('i');joy.addEventListener('pointerdown',e=>{joyId=e.pointerId;joy.setPointerCapture(e.pointerId);mobileMove.active=true});joy.addEventListener('pointermove',e=>{if(e.pointerId!==joyId)return;const r=joy.getBoundingClientRect(),dx=e.clientX-(r.left+r.width/2),dy=e.clientY-(r.top+r.height/2),len=Math.min(38,Math.hypot(dx,dy)),a=Math.atan2(dy,dx);mobileMove.x=Math.cos(a)*len/38;mobileMove.y=-Math.sin(a)*len/38;knob.style.transform=`translate(${Math.cos(a)*len}px,${Math.sin(a)*len}px)`});function joyUp(){mobileMove.active=false;mobileMove.x=mobileMove.y=0;knob.style.transform=''}joy.addEventListener('pointerup',joyUp);joy.addEventListener('pointercancel',joyUp);const look=$('#mobileLook');look.addEventListener('pointerdown',e=>{lookId=e.pointerId;lookLast=lookStart={x:e.clientX,y:e.clientY};look.setPointerCapture(e.pointerId)});look.addEventListener('pointermove',e=>{if(e.pointerId!==lookId)return;state.player.yaw-=(e.clientX-lookLast.x)*.006;state.player.pitch=clamp(state.player.pitch-(e.clientY-lookLast.y)*.006,-1.4,1.4);lookLast={x:e.clientX,y:e.clientY}});look.addEventListener('pointerup',e=>{if(Math.hypot(e.clientX-lookStart.x,e.clientY-lookStart.y)<8){if(activeInteract)interact();else if(state.slot===3)shoot();else if(state.slot===4)swingAxe()}lookId=null});$('#mobileAction').onclick=()=>activeInteract?interact():state.slot===3?shoot():swingAxe();$('#mobileJump').onclick=()=>{state.stamina=clamp(state.stamina-8,0,100)};

function gameLoop(t){requestAnimationFrame(gameLoop);const dt=Math.min(clock.getDelta(),.05);if(state.cutscene)updateTruckCutscene(dt);else if(state.running&&!state.paused){updatePlayer(dt);if(!state.interior){updateAnimals(dt);updateEnemies(dt)}else if(state.interiorMode==='mine')updateEnemies(dt);else $('#threat').classList.remove('show');updateDayNight(dt);updateWeather(dt);animateWorld(t,dt);updateHUD();autosaveTimer+=dt;if(autosaveTimer>35){saveGame();autosaveTimer=0}}renderer.render(scene,camera)}
function boot(){let p=0;const timer=setInterval(()=>{p=Math.min(100,p+8+Math.random()*14);$('#loadFill').style.width=p+'%';if(p>=100){clearInterval(timer);setTimeout(()=>{$('#loading').classList.add('hidden');$('#menu').classList.remove('hidden')},350)}},100);buildWorld();const saved=loadGame();if(saved)$('#continueGame').classList.remove('hidden');renderInventory();registerWebMCP();gameLoop(0)}
addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});boot();
})();
